### ISSUE TITLE
Add a module that allows mods to make make mod-only notes on submissions/comments

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#264]
12:45 AM \<dylan522p\> so
12:45 AM \<dylan522p\> What I would like is\
12:45 AM \<agentlame\> yeeees
12:46 AM \<dylan522p\> Basically you intergrate comments into the modquene so we mods can comment on specific reports and such without modmail and flair it and stuff too for just mods
12:46 AM \<dylan522p\> through wiki i assume
12:46 AM \<dylan522p\> sounds really complicated though
12:46 AM \<agentlame\> hrm....
12:46 AM \<dylan522p\> idea needs to be refiend obviously
12:47 AM \<dylan522p\> but its something that would be awesome
12:47 AM \<agentlame\> It could be done.  The issue is storage limitations.
12:47 AM \<dylan522p\> Yeah, idk the technical limitations
12:48 AM \<dylan522p\> just something I thought about
12:48 AM \<agentlame\> It would have to auto-purge old comments.
12:48 AM \<dylan522p\> Like once they have been aproved or removed
12:48 AM \<agentlame\> dakta: thoughts ^
12:49 AM \<agentlame\> dylan522p: oh, that would work.  I was thinking more by age.
12:49 AM \<agentlame\> Who cares about a mod not on a month-old comment/post?
12:49 AM \<dylan522p\> oh
12:49 AM \<dylan522p\> combination
12:49 AM \<dylan522p\> because modquene can get way too big sometimes
12:50 AM \<agentlame\> Well, the limitations could handle just about any modqueue.
12:50 AM \<agentlame\> The issue is more old stuff piling up.
12:50 AM \<dylan522p\> ah
12:50 AM \<dylan522p\> ok then yeah age is cool
12:51 AM \<agentlame\> dylan522p: open an issue on github.
12:51 AM \<agentlame\> Otherwise we forget shit quickly.
12:51 AM \<dylan522p\> fuck man
12:51 AM \<agentlame\> ???
12:52 AM \<dylan522p\> gotta make an account and stuff
12:52 AM \<dylan522p\> and owrd it out lol
12:53 AM \<agentlame\> I could file it for you... but we have found that people best present their own requests better than we can.
12:53 AM \<dylan522p\> pls
12:53 AM \<dylan522p\> let me be lazy
12:53 AM \<agentlame\> When we file user requests it's like "pls do x"
12:53 AM \<dylan522p\> wouldn't it be the same for me?
12:53 AM \<agentlame\> Let me be lazy?  I have to write the code. :p
12:53 AM \<dylan522p\> pls do x
12:54 AM \<dylan522p\> agentlame: but you care more about this than me

**Comment by psdtwk** [comment]
consolidated to #557
