### ISSUE TITLE
Insert big mod buttons on the native reddit link toolbar (accessable in settings) when following a link from unmod or modqueue.

### ISSUE THREAD

**Issue by noeatnosleep** [creesch/reddit-moderator-toolbox#266]
Insert big mod buttons on the native reddit link toolbar (accessable in settings) when following a link from unmod or modqueue. When clicked, have the tab close, bringing the moderator directly back to the queue list they were working on.

This toolbar, that is visible after checking the 'show reddit toolbar when following links' box in reddit preferences:

http://i.imgur.com/3YzcP8h.png

**Comment by geo1088** [comment]
This can probably be closed since the toolbar in question isn't a thing anymore

**Comment by creesch** [comment]
Truth, it is actually that at some point I'd like to build into companion.  https://github.com/creesch/reddit-companion
