### ISSUE TITLE
User notes for names in links

### ISSUE THREAD

**Issue by NotRaia** [creesch/reddit-moderator-toolbox#323]
It would be nice to be able to add tags to users linked in comments/messages like with RES. We often link reported usernames in mod mail so that we can tag them, and it would save time (and probably get more people switching from RES tags) if we could do it straight from mod mail.

Having usernotes with linked names would be especially useful when discussing bans in modmail - it'd be great to be able to have it include the link to where we discussed the ban, for reference in case asked later.

**Comment by psdtwk** [comment]
https://www.reddit.com/r/toolbox/comments/36fo0k/usernotes_for_uusernames_mentioned_in_comments/
