### ISSUE TITLE
Have links to toolbox toolbar always go to preferred domain

### ISSUE THREAD

**Issue by hermithome** [creesch/reddit-moderator-toolbox#327]
So, I'm meta-ing away, browsing shitty things stupid people say. Which means I'm looking at np.reddit.com not www.reddit.com.

I see an alert at the bottom telling me that the queue needs checking. I go to do mod work, and boom, I'm doing mod work from np.reddit.

It's super annoying. I mean, how np affects toolbox is annoying overall. It's a different domain, so different alerts and for some reason, it also unclears my modmail and treats recent read stuff as unread. But, AFAIK, those are not easy fixes, and I believe that the toolbar links are.

**Comment by agentlame** [comment]
Why is this labeled bug?  Removing bug tag and pushing to a future release.  It's a complex feature.

**Comment by creesch** [comment]
Not likely to change, complicated further by new modmail. Closing this issue.
