### ISSUE TITLE
add note ability to modmail

### ISSUE THREAD

**Issue by hermithome** [creesch/reddit-moderator-toolbox#328]
So there's already #323 which suggested something similar (global add for usernotes).

I'm looking for something much more specific. Right now, you can only add a note if someone has commented or posted in your sub (and not deleted it). If someone deletes before you can note, you're out of luck, unless you're going to mess with manual adds.

This could be easily fixed by allowing mods to add notes from modmail. I could send myself a modmail that says: "/u/ser123 did x, y and z. See this link/screenshot/whatever". Then I could go to that subreddit's modmail (not reddit.com/message/moderator but reddit.com/r/subreddit/message/moderator) and add a tag that linked to that modmail.

This would not only fix the can't add note if no subreddit link problem, but it would also give us the ability to easily keep track of prior mod discussion with or about a user.

**Comment by psdtwk** [comment]
consolidated to #557
