### ISSUE TITLE
[MB] optional feature to auto-populate ban message with permalink.

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#343]
This would be a local user setting that, if enabled, would automatically populate the ban message text field with the permalink to the post/comment/modmail the user was banned from.  Often times it's what I put there for generic trolls, if I put anything at all.  

Perhaps prefix it with "You have ban for: [permalink]"

[I had offered this as a joke reply](https://www.reddit.com/r/ideasfortheadmins/comments/2o361u/mods_must_be_required_to_give_a_reason_for/cmjeqwl?context=1), but I kinda like the idea.  Plus, if that idea ever becomes a thing, we're future proof!

**Comment by creesch** [comment]
3.x

**Comment by agentlame** [comment]
Closing in favor of the more up to date #779
