### ISSUE TITLE
[Utils] create a simple and generic messaging/event system for TB

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#385]
This is one of those big structure ideas.  Right now we use just a tiny bit of `CustomEvent` for things like the init process and reddit/RES adding items to a page.  However, I'd like to create some utility methods to make events easier, more consistent and really quick to use.  

### Example usage 1: Inter-module communication:  
   Right now, modbar and MMP check Notifier's settings in loops to update counts.  What make way more sense is Notifier should emit an event when it has a new mod mail or message.

### Example usage 2: Avoiding loops and timeouts in modules and dealing with callbacks:  
  There is (or will be in a few minutes) a much too complex loop/timeout/mess in UN manager.  The reason for it is because we have to do some really weird stuff to check that the very last usernote for the very last user has been added to the page before you can safely close the longLoad and call `noteManagerRun()`.  

  We have similar issues with callbacks in quite a few places.  Instead of making complex loops and checks for callbacks, what makes much more sense if for the module to register it's own event and consume it.

While I realize creating and consuming events is already pretty easy to do, I'd like a standard way for them to work, and to use const strings as a pseudo strong typing.  For instance, instead of using the magic string of `"TBNewThings"` all over the place, we should be using (as an example) `TBUtils.messages.NEW_THINGS`.  (We should actually be using const strings in **a lot** of places, but that's another issue.)

Anyways, this is pretty much an RFC at the moment.  Thoughts?

**Comment by agentlame** [comment]
Oh hey, I did this two releases ago.

**Comment by creesch** [comment]
can we have this documented?

**Comment by agentlame** [comment]
Someone should do that, I agree.  

In the meantime there's this: 
- https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L256, 

Utility methods: 
- https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L274

And some example usage:

Sending:

- https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modbar.js#L674

Catching:

- https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/achievements.js#L219

**Comment by agentlame** [comment]
BTW, those aren't really outstanding examples.  Here's a cooler one that I need to add to TB proper:

An action setting...  
- https://github.com/agentlame/toolbox-base/blob/master/modules/cltemplates.js#L20

That can launch part of a module:
- https://github.com/agentlame/toolbox-base/blob/master/modules/cltemplates.js#L144

What it looks like: http://i.imgur.com/EQQyJmg.png
