### ISSUE TITLE
Adjust TBui.overlay html&css for tabs on the side.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#394]
Not sure why I didn't do it before, probably because it slipped my mind. Anyway on smaller screens the amount of tabs we have now cause them to wrap to a new line which, frankly, is rather ugly. 

One complication is the way footers are generated, this will need some thought. So that's why 3.1 (or possibly 3.2)

**Comment by creesch** [comment]
3.x, no rush.

**Comment by Geo1088** [comment]
I can't find the commit now, but I know this has been implemented for 3.6.
