### ISSUE TITLE
Alphabetize the modules in Toolbox settings

### ISSUE THREAD

**Issue by amici-ursi** [creesch/reddit-moderator-toolbox#396]
Please alphabetize the modules in Toolbox settings. Both in the left pane of the settings window, and in the "Toggle Modules" tab.

**Comment by Geo1088** [comment]
@creesch is there a reason we can't just sort the elements of the list [at the end of `injectSettings`](https://github.com/creesch/reddit-moderator-toolbox/blob/c053c6e929954645cce119a8df02af3b47b7658b/extension/data/tbmodule.js#L883)? I'm writing some code to do that now, was just wondering if there's any reason that wouldn't work.

**Comment by creesch** [comment]
Toolbox settings also always needs to be first and about needs to be last.

**Comment by Geo1088** [comment]
Custom .sort() functions FTW, I was thinking about that too. The module toggle tab would also be at the top, that's doable.

**Comment by Geo1088** [comment]
713ed6b
