### ISSUE TITLE
Firefox automatic updating.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#409]
I have looked into it and it seems it might be relatively easy to host the XPI ourselves and have it automatically update. 

http://soledadpenades.com/2014/11/28/publishing-a-firefox-add-on-without-using-addons-mozilla-org/

That article even makes it more complicated than it really seems to be since you don't have to create anything of that manually: 

     cfx xpi --update-link https://example.com/addon/latest/pluginName.xpi --update-url https://example.com/addon/update_rdf/pluginName.update.rdf

https://developer.mozilla.org/en/docs/Extension_Versioning,_Update_and_Compatibility

**Comment by creesch** [comment]
I just did some preliminary testing and it seems to work, although I haven't been able to confirm it actually automatically updates (I am not sure how often firefox checks for that) I did "check for updates" which worked absolutely perfect.

**Comment by creesch** [comment]
We got approved on the mozilla store and rather quickly as well. That seems like the better way to go.

**Comment by creesch** [comment]
Uh, lets close this. Firefox will not install unsigned addons soon anyway...

**Comment by agentlame** [comment]
So many milestones.

**Comment by Dakta** [comment]
Can we get a certificate and sign our addon? We have to sign the Safari Extension already.

**Comment by agentlame** [comment]
This has been resolved for ages. :p
