### ISSUE TITLE
Move mod macros out of beta

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#422]

**Comment by agentlame** [comment]
Can we thing of any features they need?  One day I'd like to add user-configurable actions to take when sending a macro (IE: also remove the comment it is in reply to, maybe make auto-distinguish a per-macro action, etc)

But for now, they aren't all that complex.  I recall a single report of them working across subs, but can't confirm it.  If we can't confirm it before 3.1, lets just drop them out.

**Comment by creesch** [comment]
I'd love it if we somehow could trick RES into adding their markdown support stuff (Did talk a little bit with @andytuba about this) but that is not a must have. 

I'd also love it if they inserted the comment you just made... we have the template for comments so it might even be possible. 

For what we have now I think they are production ready.

**Comment by Dakta** [comment]
I still think macros should hijack the comment box, but :P
