### ISSUE TITLE
Add {mod} token to Mod Macros

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#424]
token | Definition | example
---|---|---
{mod} | The name of the mod doing the action. | psdtwk

That should be the last of the [tokens from Removal Reasons](https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/removalreasons.js#L145-153 "I think this link is right?").

A use case could be:

> Thanks for writing in to /r/{subreddit} modmail, where we _care_ about your {kind}.
> Unfortunately, your {kind} was removed because we don't allow neo-nazi bullshit in /r/{subreddit}.
> Have a nice day!
> -{mod}
> xoxo

**Comment by psdtwk** [comment]
@agentlame

**Comment by agentlame** [comment]
This one I almost feel bad about.  The issue likely took 5 mins to write.  The fix was one line of code.  :/

**Comment by psdtwk** [comment]
I spent that much time formatting the post!

**Comment by agentlame** [comment]
I had a feeling.  It reads sooo nice.  I'm sorry. <3

**Comment by creesch** [comment]
Don't feel bad, now he can copy paste it into docs ;)

**Comment by psdtwk** [comment]
lol fucking shit. it's already in docs. it's been there this whole time.

**Comment by creesch** [comment]
Oh... well uhm... then... uh disregard what I said. bye tnx!
