### ISSUE TITLE
[un manager] check if user is active mass action.

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#426]
@creesch I'm assigning this to you, since it should use the same ratelimit code as modmatrix's "load comments" but if you really don't want this, change it to me and I'll sort it out.

**Comment by creesch** [comment]
I'll have a look at the code, will be next weekend most likely before I have properly time for it though.

**Comment by creesch** [comment]
Ok, I am hoping I will have time this weekend.
