### ISSUE TITLE
[nuke] fix deprecation issues 

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#430]
For the most part, a ton of the code needs to use jQuery to be consistent with other TB code.  Right now it throws console errors and is hard to extend/change in relation to the rest of TB.

**Comment by Dakta** [comment]
Yeah, that's my fault, I just dropped it in as-is and didn't bother fixing anything because it just needs a complete rewrite.

**Comment by Dakta** [comment]
I'm working on this currently.

**Comment by Dakta** [comment]
Needs some testing and tweaking to improve robustness, but this should work about as well as the previous one. May need to adjust some of the timing to ensure there is sufficient wait after loading more comments and after removing.

Still needs to be upgraded to call the API removal method, which will be much more robust than poking the HTML like this.

**Comment by agentlame** [comment]
@TheEnigmaBlade 

Is nuke working correctly in FF without console fuckery?

**Comment by TheEnigmaBlade** [comment]
Latest repository version worked fine in FF.

**Comment by agentlame** [comment]
I think this is safe to close.  If there's another issue with nuke in FF, it's worth a new issue.
