### ISSUE TITLE
[/r/toolbox] abandon /w/download in favor of /w/get

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#431]
It's super confusing that we have both /r/toolbox/w/download and /r/toolbox/w/get.  We need to kill one of them in all links and code.  /w/get has always been more actively maintained and should be the go-to in code and sub links.

**Comment by creesch** [comment]
yeah, the only reason we have both is to prevent some asshole with malicious intend of inserting his own links.

**Comment by agentlame** [comment]
lol, I did this forever ago.
