### ISSUE TITLE
Make all non-modal dialogs user-movable & make the current ones use "dragable: true" 

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#433]
Currently only the debug window is movable, while other non-modal dialogs like the usernotes dialog can't be moved. Would be nice QoL change, but it's not major.

**Comment by agentlame** [comment]
Personal Notes is also.   But I agree that it'd be nice now that we have a solid solution for movable windows.

**Comment by agentlame** [comment]
This also applies to usernotes, domain tagger and maybe others.

**Comment by creesch** [comment]
Please note that I am still not sure all of these should be movable. 

side note: history button windows probably needs some testing now

**Comment by Garethp** [comment]
This functionality will allow all dialogs that use the TB.popup function to make their things movable. The only reason I turned it off by default, and only enabled it for history notes, was that history notes being movable was marked for 3.1, while the others weren't, and we're in a feature freeze

**Comment by agentlame** [comment]
That's fine.  But the issue still isn't closed until it's done.  That's how we forget about things.

**Comment by Garethp** [comment]
Fair point. I'll keep it in mind

**Comment by creesch** [comment]
I adjusted the title so we also don't forget to make the ones that are already dragable make make use of the shiny new "dragable: true" thingie.
