### ISSUE TITLE
[queue tools] The sticky toolbar does not play nice with RES' sticky subreddit bar

### ISSUE THREAD

**Issue by aperson** [creesch/reddit-moderator-toolbox#434]
http://i.imgur.com/3uQ3UMp.png

As seen in the image, the sticky toolbar is underneath and partially covered by the sticky subreddit bar.

Paging @andytuba as well, as requested.

**Comment by andytuba** [comment]
RES can add one of four body classes. I think the subbar and subreddit header are the only ones of interest here. 


Option description / description
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/733e9bed0bcddf000c8c501aefe4d9f49fa967ae/lib/modules/betteReddit.js#L89 

Body classes
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/733e9bed0bcddf000c8c501aefe4d9f49fa967ae/lib/modules/betteReddit.js#L245
