### ISSUE TITLE
[metrics] make the the tab a drop down of different metrics sites.

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#436]
Instead of a single site for user stats and sub stats, the tab should be a drop down for all the ones we know of.  Some will be on both tabs since some sites do user and sub stats, some will only show on a sub page or a user page.

The dropdown shouldn't an actual HTML dropdown, but rather a hidden `<div>` that shows a list of the sites when the tab is clicked.

Please add comments to this issue with all the meta/metric reddit sites and if they apply to users, subreddits, or both.

**Comment by psdtwk** [comment]
* http://0bservat0ry.com/reddit.html
* http://www.redditinvestigator.com/
* http://www.redditinsight.com/
* http://www.snoopsnoo.com
* http://www.karmawhores.net/
* http://www.redective.com/
* http://www.google.com

**Comment by agentlame** [comment]
Subreddit Info:

* http://metareddit.com/r/{sub}
* http://redditmetrics.com/r/{sub}

**Comment by agentlame** [comment]
Users:

* http://reddit.dataoverload.de/karmastats/#{user}

* http://www.karmalb.com/user/{user}
