### ISSUE TITLE
Domain Notes

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#442]
Exactly like User Notes, except for domains.

I'd like to see full notes on domains so we can write things like, "maybe spam?" or "this domain is known for shitposting, keep an eye on it." They could reference actual permalinks like User Notes do. The note color should also work like it does in User Notes (or maybe take color from Domain Tagger?)

**Comment by creesch** [comment]
Good idea, although there is a small issue with domains and subdomains. In some cases you want to leave notes on subdomains (wordpress websites for example) where in other examples the subdomains are effectively the same website. 


I think that can be handled by an option in the case of subdomains that says something like "Leave note for  main domain []" and in case of subdomains also show the notes for the main domain if they are there

**Comment by k3n** [comment]
+1 here as well, I've thought about this before too.

**Comment by Dakta** [comment]
Subdomains can be pretty much arbitrarily deep, although most of the time they're not used more than one or two levels.

Based on this, perhaps it might make sense to use a wildcard syntax for subdomains.

**Comment by psdtwk** [comment]
Including a link to @agentlame and my dev huddle on notes in general because it's worth keeping in mind.

https://www.reddit.com/r/tb_dev/comments/2tfjvf/future_usernotes_improvements/

**Comment by psdtwk** [comment]
consolidated to #557
