### ISSUE TITLE
Hide advanced Removal Reason settings

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#444]
@agentlame 

get reason from /r/:	(WARNING: this setting overrides all other settings.)  
logsub /r/:	
pmsubject:	
logtitle:	
bantitle:	
logreason:

**Comment by agentlame** [comment]
>@agentlame

Or you could just assign it. :p

**Comment by psdtwk** [comment]
If you had said, "assign it to me." >:|

**Comment by psdtwk** [comment]
Rolling this into #418 because it's a better number.

**Comment by psdtwk** [comment]
reopening because al says they're different and I trust him because he said so.

**Comment by agentlame** [comment]
To be clear on this: the "Removal Reasons Settings" tab needs to hide like five settings behind a "Show Advanced" button.

Issue #418 is about defining various settings with an 'advanced' flag, and having an option that is "show advanced settings".  Much like the "show beta features" option and corresponding flag.
