### ISSUE TITLE
[TB Config] Removal reason titles change class when reason is edited

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#445]
After editing a removal reason, the class of the reason's title changes from `reason-title` (no underline) to `removal-title` (dotted underline). I'm not sure which is intended.

Unrelated, but `span.removal-reason-label` should probably be merged with its child `span` as a matter of keeping things tidy.

**Comment by agentlame** [comment]
Is this in dev or stable also?

**Comment by psdtwk** [comment]
reopened because accidently closed via typo in commit comment.

**Comment by agentlame** [comment]
>reopened because @andytuba is wrong

FTFY

**Comment by andytuba** [comment]
rabble rabble rabble
