### ISSUE TITLE
Magenta color option doesn't work in domain tagger

### ISSUE THREAD

**Issue by xminusone** [creesch/reddit-moderator-toolbox#448]
When a domain tag's color is set to magenta using the [T] button, the color is added to the /wiki/toolbox page as DC00C8 rather than #DC00C8, causing the domain tag not to show unless the # is manually added.  All other colors have a # in front of them, and seem to work correctly.

**Comment by psdtwk** [comment]
Hopefully fixed here: https://github.com/creesch/reddit-moderator-toolbox/commit/f20662a9f50ab3189da8d1bd741cbb33ff4404ac
