### ISSUE TITLE
Add an option to skip reddit's "are you sure" dialog when removing a comment

### ISSUE THREAD

**Issue by amici-ursi** [creesch/reddit-moderator-toolbox#461]

**Comment by agentlame** [comment]
Should be part of better buttons.

**Comment by TheEnigmaBlade** [comment]
I *do* have a userscript that removes the remove comfirmation, but I didn't add it due to conflicting behavior in removal reasons. Currently my userscript overrides removal reasons and you have to click twice to open the dialog (which I think is quite nice).

**Comment by psdtwk** [comment]
You raise a good point about Removal Reasons. Do you change the text of "remove" to "add reason" after you click it?

**Comment by Geo1088** [comment]
Looks like this was done in 2f067bc.
