### ISSUE TITLE
Refactor HistoryButton Module

### ISSUE THREAD

**Issue by Garethp** [creesch/reddit-moderator-toolbox#466]
Shit needs rewriting yo

**Comment by Dakta** [comment]
Yeah, it's a holdover from back when it used to be part of DEADb33f's ModTools userscript. Just needs a full rewrite.

**Comment by creesch** [comment]
@dakta that is why @Garethp made this issue, since he is going to work on it ;)

**Comment by creesch** [comment]
@Garethp if I am mom @dakta is the dad who went out to get a packet of cigarettes a long time ago :P

**Comment by Dakta** [comment]
Wasn't that just this afternoon?

**Comment by Garethp** [comment]
I thought @dakta was dad in the sense that @creesch is sleeping with him, because @creesch can't get over dad leaving for smokes.

**Comment by Garethp** [comment]
Who is this @Dakta you speak of?
