### ISSUE TITLE
Banning users through the mod button with a ban note will silently fail if the user won't receive a ban PM

### ISSUE THREAD

**Issue by xminusone** [creesch/reddit-moderator-toolbox#469]
It looks like this change may have affected the mod button's ban function: http://redd.it/2uxdcx

If I try to ban a user who will not receive a ban message (so the ban will trigger an error on the "ban users" page) with the mod button, and add a ban message, it appears that the ban succeeded, but the ban is not actually applied and does not show up on the "ban users" page or in the modlog.  It appears the same issue might exist if the user is a mod of the subreddit you're attempting to ban them from.

Debug console output when I attempt to ban:

```
Toolbox version: 3.0.5, Browser: chrome, Extension: true, Beta features: true

001 [TBinit]: TBModule has TBUtils
002 [TBinit]: TBModule loaded, getting TBStorage
003 [TBinit]: TBModule has TBStorage, loading modules
004 [TBinit]: Loading Notifier module
005 [TBinit]: Loading Domain Tagger module
006 [anonymous function]: getting new subs.
007 [TBinit]: Loading Mod Button module
008 [TBUtils]: Enqueueing getModSubs callback
009 [TBinit]: Loading History Button module
010 [TBinit]: Loading Syntax Highlighter module
011 [TBinit]: Loading Comment Nuke module
012 [TBinit]: Loading Toolbox UI (modbar) module
013 [TBUtils]: Enqueueing getModSubs callback
014 [TBinit]: Loading User Notes module
015 [TBUtils]: Enqueueing getModSubs callback
016 [TBinit]: Loading Comments module
017 [TBUtils]: Enqueueing getModSubs callback
018 [TBinit]: Loading Toolbox Config module
019 [TBinit]: Loading Mod Log Matrix module
020 [TBinit]: Loading Removal Reasons module
021 [TBinit]: Loading Mod Macros module
022 [TBUtils]: Enqueueing getModSubs callback
023 [TBinit]: Loading Realtime Reddit module
024 [TBinit]: Loading Personal Notes module
025 [TBinit]: Loading Queue Tools module
026 [TBUtils]: Wiki page error: Forbidden
027 [getSubsResult]: calling callback 
028 [getSubsResult]: calling callback notifierinit
029 [getSubsResult]: calling callback 
030 [getSubsResult]: calling callback 
031 [getSubsResult]: calling callback 
032 [ModButton]: banning from: nottheonion
033 [ModButton]: completed ban round
034 [ModButton]: complete
```

Relevant discussion from IRC:

`7:09:15 PM <andytuba> okay the "ban" api endpoint is sending back a 200 "response okay" but with errors[0] = [ "USER_BAN_NO_MESSAGE", "blah blah blah remove the note", "ban_message" ]`

`7:11:47 PM <andytuba> psdtwk: same issue if trying to ban a mod — error message is [ "already_moderator" … ] but toolbox swallows the error`

**Comment by psdtwk** [comment]
Relevant changelog post: http://www.reddit.com/r/changelog/comments/2uxdcx/reddit_change_changes_to_the_ban_users_page_for/

> if you fill out the "note to include in ban PM" box, but are banning a user that won't actually be sent a ban message because they don't meet those conditions, you will no longer be able to ban them until you clear out that box.

**Comment by andytuba** [comment]
more generally "... will silently fail if the ban fails for any reason."

**Comment by creesch** [comment]
Hrm, that is no good. Also why the hell is it failing silently... it is supposed to yell at you if a ban failed and ask you to try again. (though that might just be for mass actions). 
I guess it might be hotfix time. 

@agentlame

**Comment by agentlame** [comment]
@creesch *if the user won't receive a PM*

**Comment by creesch** [comment]
Right, so only global ban is affected. Which is probably just a small group of our users. 

3.2 it is then
