### ISSUE TITLE
Queue kitteh doesn't like Firefox :(

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#471]
The `tb-kitteh` class is properly applied to the element, but the CSS isn't applied (doesn't show up in any dev tools). Still works fine in Chrome.

**Comment by TheEnigmaBlade** [comment]
It seems the fault lies with `background-image`. Attempting to add a rule via Firebug shows some CSS is applied (probably the kitteh CSS) but is just not working:

![](http://i.imgur.com/ReOks15.png)

Setting that custom `background-image` to be `!important` overrides the problem CSS and kitteh works.

I just don't know why the extension CSS is having problems and how to fix it.

**Comment by creesch** [comment]
We don't need relative urls, just use https. Relative urls have presented issue with chrome as well with similar stuff. In fact I am 99% sure it was not a relative url before. 

In fact f35ecc2a23747246f34940d181dd652e83e3e74c broke it.

**Comment by psdtwk** [comment]
@TheEnigmaBlade Didn't you fix this? cbaf9db680e83ef5b2940a7671faf9d45f0fee42
