### ISSUE TITLE
have a 'blacklist' for subs not to include in a global ban OR allow user-created ban groups

### ISSUE THREAD

**Issue by noeatnosleep** [creesch/reddit-moderator-toolbox#472]
I know we may not support globals in the future, but I'd like to be able to global without banning from certain subreddits. 

OR.... we could get rid of globals and allow user-created ban groups.

**Comment by creesch** [comment]
I reformatted the title to be a proper issue. 

Having a blacklist would be relatively easy to implement. 

The second one would actually be preferred but takes a little but more work.

**Comment by noeatnosleep** [comment]
Thanks for the fix. 

I could maybe try and write the setting for it if you told me where you want it to be.

**Comment by creesch** [comment]
I'll be rather busy until at least Tuesday since I am studying for a certificate exam. Which is actually why I am active here, need a bit of a break. Or possibly I am just procrastinating ;)

Anyway, I might have some time later in the week (no promises) to sit down and help out there.

**Comment by noeatnosleep** [comment]
By 'tell me where you want it to be' I mean 'in notifier' or something, not actually showing me in the code. =)

**Comment by creesch** [comment]
it is a modbutton setting ;)

**Comment by noeatnosleep** [comment]
OK, no promises, but if I can get home after work and sit down, I'll play with it. If not we can dig around next week. =)

**Comment by creesch** [comment]
Alright, basically you want to reproduce the "save subs" setting as it is found here: 

- https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modbutton.js#L9

And then remove the subs in your blacklist from the mysubs results somewhere around here 

- https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modbutton.js#L416 

With something like [this](http://stackoverflow.com/a/14930567)

**Comment by Dakta** [comment]
> OR.... we could get rid of globals and allow user-created ban groups.

We have some ideas about this, for sure.

**Comment by agentlame** [comment]
No blacklist.  The Global Action functionality is/will/should be replaced by 'context lists'.  @Dakta has a thread about this in /r/tb_dev.

**Comment by psdtwk** [comment]
> @Dakta has a thread about this in /r/tb_dev.

https://www.reddit.com/r/tb_dev/comments/2mti5d/moderating_many_subreddits

**Comment by noeatnosleep** [comment]
Do we want to defer this again?

**Comment by agentlame** [comment]
Yes, it's a super non-trivial change.
