### ISSUE TITLE
Unable to close User History dialog on the first item in the unmoderated queue since it appears behind the RES "Use subreddit style" checkbox

### ISSUE THREAD

**Issue by xminusone** [creesch/reddit-moderator-toolbox#474]
If I use the [H] button for the first item in my unmoderated queue (or modqueue, presumably), I'm unable to click the X to close the User History dialog since it appears behind the RES checkbox that allows you to turn off subreddit styles.  This is intermittent depending on the length of the user's name and how old the post is, since that affects the position of the [H] button.  The only way to close out of it is either by refreshing the page or by finding a small sliver of the X button that may be sticking out.

Screenshots:  http://imgur.com/a/82iPW

Browser Info:  
Chrome OS Version 40.0.2214.114 (64-bit)
Platform 6457.94.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.89.0

Resolution:  1366x768

Toolbox Version:  3.0.5

RES Version: v4.5.4

**Comment by creesch** [comment]
Heh, that is a very specific bug that has much to do with your screen resolution. I am not entirely sure we will be fixing this since it means we have to raise the z-index of those windows to a rather high count. 

I'll keep the issue open though since it is likely a few more people have the same issue and we might end up working around it anyway.

**Comment by Lurlur** [comment]
Does it to me too. But only when there's no banner ad in the sidebar.

**Comment by Garethp** [comment]
@creesch: Can we have Javascript detect if they would overlap, then if so manually *lower* the Z-Index for that, instead of raising ours?

**Comment by ArrestedDevelopment** [comment]
Maybe you can get the position of the close button, and put the position into [`document.elementFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) to see if there's anything drawn on top of it?

**Comment by creesch** [comment]
that seems like a whole lot of trouble for a fringe case if I am being perfectly honest.

**Comment by agentlame** [comment]
#509 fixes this.  Move the window, click close.

**Comment by creesch** [comment]
oh it does actually, good job team!
