### ISSUE TITLE
Clicking on history button opens new blank tab in Firefox

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#475]
The dialog is opened properly on the page, but a new blank tab is also opened at the same time.

**Comment by psdtwk** [comment]
Which Toolbox version? I can't duplicate this on live.

**Comment by creesch** [comment]
It is likely a firefox issue, sounds like a problem I ran into a while ago.

**Comment by TheEnigmaBlade** [comment]
It happens in both the beta build (36) and alpha build (37).

**Comment by creesch** [comment]
Doesn't seem to be an issue anymore.
