### ISSUE TITLE
[UN] Saving may use outdated usernotes cache, erasing previously added notes

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#481]
Simply saving a note on User A and then saving a note on User B will use an outdated cache and the note on User A will be erased.

The cache should be updated or the notes should be reloaded before saving. This is the current flow that *should not* be happening in this manner:

    001 [UserNotes]: notes found in cache
    002 [UserNotes]: Saving usernotes to wiki...
    003 [postToWiki]: Posting /r/leagueoflegends/api/wiki/edit/usernotes
    004 [UserNotes]: Success!
    005 [UserNotes]: notes found in cache

**Comment by creesch** [comment]
@psdtwk same bug as you have I guess. I'll try to squish it for 3.1

**Comment by creesch** [comment]
Seems like someone already fixed this https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/usernotes.js#L861

Cache is updated before notes are saved. 

@TheEnigmaBlade is this still an issue or something you fixed along the way and forgot to close?

**Comment by TheEnigmaBlade** [comment]
I haven't noticed it recently, so I guess it's fixed.
