### ISSUE TITLE
[UN] Links erased on all previous notes

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#482]
Adding a new note will save the note's link properly, but all previous notes will have their links erased.

**Comment by agentlame** [comment]
In dev or stable?  This is likely related to my restructuring of `usernotes.js` in 3.1 dev.  squish/unsquish have issues.

**Comment by creesch** [comment]
@TheEnigmaBlade is this still an issue?
