### ISSUE TITLE
Modmail does not mark as read after being read

### ISSUE THREAD

**Issue by LiveBeef** [creesch/reddit-moderator-toolbox#484]
Toolbox is hit-and-miss about marking unread modmail messages as read after being viewed. Many times, after viewing all new modmail messages and navigating away from the page, the icon will remain red in both the userbox at the top (RES) and in the toolbox itself at the bottom. Upon returning to modmail, the same messages will still be marked [new]. Issue is fixable by disabling the extension in Chrome and going to modmail.

OS: Windows 8.1 64-bit
Browser: Chrome v40.0.2214.115 m
Toolbox v3.0.5

**Comment by agentlame** [comment]
>reddit is hit-and-miss about marking unread modmail messages as read after being viewed.

ftfy

> the icon will remain red in both the userbox at the top (RES) 

top bar **isn't** RES, it's reddit.  


This is a reddit issue.

**Comment by LiveBeef** [comment]
Modmail marks as read perfectly fine when the extension is disabled, only stays unread persistently when the extension is active. Is not a reddit issue.

**Comment by agentlame** [comment]
If you can be more clear about the issue, I'm happy to re-open it.  But as phrased, it's not a TB issue.

**Comment by LiveBeef** [comment]
I'm unsure of what needs clarifying, but I'll try: When the TB chrome extension is disabled, when I click on a modmail icon that shows unread messages, read the messages, and then leave the page, the modmail icon stays gray until I get new mail. With the extension activated, when I click on a red modmail icon, read the messages and leave the page, the icon either stays red or becomes gray only to return to red without having received new mail later. When I return to modmail with the extension installed, the exact messages that I have already read are still marked [NEW], even messages that I have typed myself. This is usually not fixed by leaving the page and returning additional times, although it does eventually return to gray. Deactivating the extension and returning to modmail reliably marks all messages as read. I have yet to pin down the cause but the issue is TB-side, not reddit-side. Let me know if it still doesn't make sense.
