### ISSUE TITLE
Historybutton - report to /r/spam button missing unless "get comment history" is clicked.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#487]
Title says it all.

**Comment by Garethp** [comment]
Can you post a screenshot, and what branch you're on? I've checked out master, but I'm not getting this issue

**Comment by creesch** [comment]
I am on master, using chrome. I'll screenshot it when I get home. 

One more observation, it doesn't always malfunction. I haven't been able to pinpoint in what situations it does or doesn't work though.

**Comment by agentlame** [comment]
I'm also unable to reproduce this.

**Comment by creesch** [comment]
@Garethp @agentlame 

http://i.imgur.com/nnLo61t.png <-- Historybutton is done and long load no longer there but the buttons are missing. 


http://i.imgur.com/lixWCX5.png <-- Once I click on the comment link (in this case with the right button since I wanted to inspect) they suddenly do show. 

I couldn't find anything odd in the code at first glance.
