### ISSUE TITLE
Display Ban Status in Modmail

### ISSUE THREAD

**Issue by Dakta** [creesch/reddit-moderator-toolbox#489]
> Display, next to the username, if that user is currently banned, and what the ban reason was. This is a big one that can prevent a lot of mistakes. ([Source](https://www.reddit.com/r/modnews/comments/317ymj/moderators_open_call_for_feedback_on_modmail/cpz60ap))

This sounds like a really great feature, and since the modmail overhaul is a ways off (and this might never make it in there anyways), I'd like to throw something together for this.

**Comment by agentlame** [comment]
That's a LOT of extra GETs per-load of modmail.  I'm not opposed, but it needs to be super efficient and cashed.

**Comment by agentlame** [comment]
I think the short cache would be enough.  Just so its not a new GET for each modmail page load.

**Comment by creesch** [comment]
Or we could make it a button "display ban status" the majority of modmail isn't from banned users so having to do requests for that seems silly to me, even if it is cached.

**Comment by agentlame** [comment]
But that is already one-click away with mod button.  Plus le UI clutter.

Let's defer this for now... might need some baking.

**Comment by Dakta** [comment]
This is potentially one GET per username. We might be able to optimize for subs with small ban lists if we just get the entire ban list, but then that's at least one GET per subreddit.

You're right, even with the most reasonable caching it'd be too much. With more aggressive caching it'd be OK, but that introduces problems with cache invalidation.

I concur, defer until we figure out something clever.

**Comment by Geo1088** [comment]
Closing since this is built into new modmail.
