### ISSUE TITLE
Mod Button competes with RES's "hide child comments"

### ISSUE THREAD

**Issue by Dakta** [creesch/reddit-moderator-toolbox#492]
[Example](http://i.imgur.com/X8eQKa4.png).

This is entirely a limitation of how we insert the "mod" button currently (which I wrote), which is to count some number of list items from the end of `.flat-list.buttons`. A smarter check would be to insert before the reply button directly, with support for internationalization:

    $('.flat-list.buttons a[onClick="return reply(this)"]')

As an aside, @andytuba are y'all sure you want to put "hide child comments" after "reply"? Generally I've found that putting anything after "reply" just annoys users who go for "reply" by reflex, because they click the last list item before checking what it is. Sticking it up next to the regular collapse button doesn't make sense, but I feel like there's got to be a better place.

**Comment by andytuba** [comment]
i hate the placement of the hide child comments button too.  i don't think i've heard people complaining about that particular button. i don't really know what to do about all of RES's buttons except add an `&nbsp;` after the reply button and shove everything to the right, with an option for people to put everything in the crappy legacy locations.

**Comment by Dakta** [comment]
Sorry man all I have is just make another row of `.flat-list.buttons` that aligns right instead of left and throw RES stuff in there. But that just seems like heaps of trouble. If you could do it cleanly I'd say just make them float right inside the existing row of buttons, but I know CSS and I know that'll be a pain.
