### ISSUE TITLE
Mod button shows up on comments but not posts

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#493]
Fairly self-explanatory. I haven't tried the latest version in Chrome, but I've tried it on two versions of Firefox, one being a fresh usage of TB.

**Comment by Dakta** [comment]
Just checked in Safari after pulling. It's this: https://github.com/creesch/reddit-moderator-toolbox/commit/6c2ec3c78b1be282b098a631a2d66070f1ff4fcc It also breaks functionality in modmail.

I totally should have seen that coming.
