### ISSUE TITLE
double check wiki api callback error handling

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#495]
11:51 AM \<creesch> https://github.com/creesch/reddit-moderator-toolbox/commit/c56b9db4e81974c7c668b109c029256a7988923b
11:53 AM \<creesch> tbutils line 988 
11:56 AM \<agentlame> creesch: that may cause a huge issue with WIKI error checking.
11:56 AM \<agentlame> We depend on the exact responseText.
11:58 AM \<agentlame> https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/usernotes.js#L640
11:58 AM \<agentlame> https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L48
11:59 AM \<agentlame> 'NO_WIKI_PAGE' is err.responseText for that error.

**Comment by creesch** [comment]
I just noticed, the thing you were worried about is in regards to reading a wiki page, not writing. The writing function has entirely different error handling as the reading function, the latter is also the only one where I made changes. 

I'll keep this open and double check to be sure, but afaik it is fine.

**Comment by agentlame** [comment]
Ah, you're correct.

**Comment by agentlame** [comment]
I think we can safely close this.
