### ISSUE TITLE
sub-defined usernote templates

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#498]
This is deferred, but not a bad idea, because it contributes to the ever-an-issue wiki space problem.

Basically, subs can define common usernotes which can be stored as constants in the schema.  

More here: https://www.reddit.com/r/toolbox/comments/33sn33/request_preset_user_note_options_to_choose_from/

A usernote template should include:

- Note text (required)
- Tag type (optional)

They should be configured via tbconfig.

This will be a bit of an engineering task, since ConstMgr uses simple ints as keys.  Meaning you could have an issue if someone saves a usernote of just "1" which would be translated to Constant User Note ID: 1.   Sure, that is unlikely, but something to consider in design and testing.

**Comment by TheEnigmaBlade** [comment]
Neat, I can close this now.
