### ISSUE TITLE
[MMP] NER causes MMP to rerun on old pages

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#500]
This causes the appearance of multiple [NEW] tags on old pages.

![](http://i.imgur.com/fGGLl1J.png)

**Comment by agentlame** [comment]
This seems really similar to #499.

**Comment by creesch** [comment]
@TheEnigmaBlade are you sure you don't have two versions of toolbox running somehow?  It looks really similar to what happens when I have toolbox from the chrome store and the dev version enabled.

**Comment by agentlame** [comment]
Confirmed.  I'm checking it out.
