### ISSUE TITLE
[history] should use longLoadNonPersistent instead or longLoadSpinner

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#502]
Because closing the HB pop-up shouldn't lock the page.

Also, for the love of fuck, these things need renamed.

**Comment by creesch** [comment]
This doesn't sound like a fix... long load should just stop when you close the popup. But it should be persistent since there is still background things happening...

**Comment by agentlame** [comment]
It's a quick fix for now.  Besides, it shouldn't use the blocking one anyways, by your standards.

**Comment by creesch** [comment]
No it actually should since it is a user initiated action that performs a background operation which will report back the info once it is done.
