### ISSUE TITLE
[Config] Use old automod config page if $soon > $notSoonEnough

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#504]
Find out when @Deimos expects to have wikis converted to the new automod page.  If it's more than a few weeks, release 3.1 with old AM support and change it in a future point release.

**Comment by creesch** [comment]
Nah, soon people will be automatically converted and I don't want extra code to detect something that soon will be gone anyway.

**Comment by agentlame** [comment]
Any update on this?

**Comment by Deimos** [comment]
I'm converting everyone this week.

**Comment by agentlame** [comment]
Not who I expected to answer, but thanks!

Closing this, we'll stick with the new support.
