### ISSUE TITLE
Unmoderated counter needs to have setting for /f/mod/

### ISSUE THREAD

**Issue by noeatnosleep** [creesch/reddit-moderator-toolbox#505]
The unmod button needs a setting for http://www.reddit.com/me/f/mod/about/unmoderated/. 

I've looked at it but it's tied to stuff I don't understand, and the count also doesn't work right. 

I'd love to help, but I can't figure it out on my own at my current skill level.

**Comment by psdtwk** [comment]
@noeatnosleep What's the difference between `/me/f/mod` and creating multireddits like `/r/mod-politics` or `/r/toolbox+texas`?

**Comment by andytuba** [comment]
`/me/f/mod` will store the `-politics`  on reddit servers.

**Comment by creesch** [comment]
indeed, it is just a nifty way of making tbings cleaner. I'll make it work :)

**Comment by Dakta** [comment]
For reference: https://www.reddit.com/r/toolbox/comments/369p6y/is_it_possible_to_have_the_unmoderated_counter_in/

**Comment by noeatnosleep** [comment]
Awesome!

**Comment by creesch** [comment]
yw
