### ISSUE TITLE
Usernotes editing needs to re-blobify when saving v6

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#511]
I think. I never got around to checking.

Other than this, backwards compatibility and upgrading is looking good. The only thing we need to be wary of is older toolbox versions not knowing how to handle newer schemas (they like to erase the wiki page).

**Comment by agentlame** [comment]
Right now the editor doesn't de-blobify them.  Is this something we even want at this point?

**Comment by creesch** [comment]
Well, if the wiki is in the new schema?

**Comment by agentlame** [comment]
Yes, it will use S5.  WhIch is new schema.  But it will not use S6 (which is zlib).

**Comment by agentlame** [comment]
@TheEnigmaBlade does this issue still mean anything?

**Comment by TheEnigmaBlade** [comment]
Somewhat. The usernote editing portion of toolbox config for a subreddit doesn't deblobify and reblobify the subreddit's notes, so the feature is pretty useless from S6 onwards. Ideally, it should convert it to a non-blobified pseudo-schema (like S5), allow the user to edit it in that schema, and convert back to S6 when the user saves.

Currently it's just this:

![](http://i.imgur.com/FQilzYP.png)

**Comment by creesch** [comment]
That doesn't look very helpful indeed... A quick fix would be to hide that tab entirely if the schema is v6, considering that we now have a GUI for editing usernotes anyway we might opt to remove this particular tab altogether.

**Comment by TheEnigmaBlade** [comment]
I already talked to @agentlame on IRC. The "edit user notes" and "edit toolbox config" are hidden by default as advanced settings in 3.2, which makes this issue non-blocking for the 3.2 release.

**Comment by psdtwk** [comment]
> The "edit user notes" and "edit toolbox config" are hidden by default as advanced settings in 3.2

The beauty brings a tear to the eye ![snapshot15](https://cloud.githubusercontent.com/assets/6052722/8631595/1898ece6-2740-11e5-9bd2-8f3169c29f26.png)

**Comment by agentlame** [comment]
@psdtwk like 70% of the features I write are just to make you happy.

**Comment by psdtwk** [comment]
ilu bby
