### ISSUE TITLE
[toolbox] make a new logo

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#520]
We need a new logo for two reasons:

1. We don't have (or want) the [rights to use Snoo](https://www.reddit.com/wiki/licensing#wiki_a_licensing_agreement_is_required_in_order_to.3A).

2. Related to #519, toolbox is always to be stylized in lowercase (same as reddit) going forward.  Our current logo is a Snoo with an uppercase T on its belly.

I'm tentatively assigning this to papa bear. **However, I would also be interested in hearing some thoughts about holding logo design contest.**

**Comment by creesch** [comment]
I'll get us a new logo, I am not a fan of contests for this sort of stuff personally.

**Comment by creesch** [comment]
done

**Comment by agentlame** [comment]
Does this still need updated?  https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbui.js#L88
