### ISSUE TITLE
[modbar] toolbox's modbar covers reddit beta's widget

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#521]
https://www.reddit.com/r/toolbox/comments/358kx8/what_is_this_this_is_unreadable_half_of_the_text/

**Comment by agentlame** [comment]
I don't feel we should respond to beta.reddit.com issues.  The features are likely to change, and we can't respond to every iteration.

@creesch thoughts?

**Comment by creesch** [comment]
Agreed, I do think we should enable beta though so we are properly aware of things in beta. 

In this case it should be an easy css fix whenever they roll it out, or people collapes their bar.

**Comment by agentlame** [comment]
For sure.  I turned it on as soon as I saw the post.
