### ISSUE TITLE
Removal reason PM fails silently

### ISSUE THREAD

**Issue by GermainZ** [creesch/reddit-moderator-toolbox#522]
This is with the "PM" checkbox selected (but not "as /r/subreddit").

Removing a submission this way always **seems** to succeed (Toolbox says
"Saved"). However, if I check <http://www.reddit.com/message/sent/>, I can see
that roughly half of my removals didn't actually send a PM.

**Comment by creesch** [comment]
Hrm... I wonder if they used the same code as ban messages... meaning that it doesn't work for people that haven't earned any karma yet in that specific sub.

**Comment by creesch** [comment]
nope, that is not it.

**Comment by creesch** [comment]
wait, I am stupid... **not as subreddit**

**Comment by agentlame** [comment]
L O L

**Comment by creesch** [comment]
I can't reproduce this one, tried several configurations but simply can't.
