### ISSUE TITLE
[tbui] longLoadSpinner should not show progress bar; longLoadNonPersistent should not show the spinner big text.

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#523]
That's it.

**Comment by agentlame** [comment]
In the first case, having both is redundant.  In the second, the large box is intrusive (IE: loading mod mail).

**Comment by creesch** [comment]
I don't agree

**Comment by creesch** [comment]
to be a bit more complete,  the little window alone I don't think is enough and I personally do enjoy random feedback on modmail load.

**Comment by agentlame** [comment]
No it's not.  They mean completely different things.  Which is why they are different functions in the first place.

**Comment by creesch** [comment]
They are not completely different... they are based on the same thing and are both intended to attend the user to the fact that toolbox is still doing stuff. The difference is that one will not prevent the user from moving away from the page. 

Just to be clear, I rather keep the blue bar at the bottom in both, I'd be willing to consider removing the new random feedback from the non persistent version.

**Comment by creesch** [comment]
As per discussion on irc https://github.com/creesch/reddit-moderator-toolbox/commit/0674bccf7f75affb2a76bea20de02e1e8b72ec89
