### ISSUE TITLE
[achievements]  support links (<a href="example.com">) in achievement setting page.

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#524]
There are many reasons to support linking to something.  Be it a gif, a youtube vid or a modmail message on reddit.  Example: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/achievements.js#L190

**Comment by TheEnigmaBlade** [comment]
I don't be able to get to this for another week if you assign it to me for 3.1

**Comment by agentlame** [comment]
@TheEnigmaBlade  I'll try to get it tomorrow.  If not, we'll let it go until 3.2.

**Comment by agentlame** [comment]
@TheEnigmaBlade but 4reel, think of all the anime gifs you could link to!!!

**Comment by TheEnigmaBlade** [comment]
![](http://i.imgur.com/oPwGQ6f.gif)

**Comment by agentlame** [comment]
Exactly!
