### ISSUE TITLE
"unanswered" tab doesn't include unanswered replies to a ban message

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#525]

**Comment by agentlame** [comment]
Uh, there's no way to do this.  Modmail doesn't show ban messages until they have been replied to.

**Comment by agentlame** [comment]
Oh, I see what you're saying.  "Unanswered" just looks for messages with no replies.  Ban messages that have been replied to have one message.

Reopen this if you want, but it's a lot of extra work to make something that is very simple have a check for just ban messages.

**Comment by TheEnigmaBlade** [comment]
It's not a major issue, but I think it would be good to include at some point for consistency.
