### ISSUE TITLE
MMP does not work on /r/subredditname/about/message/inbox

### ISSUE THREAD

**Issue by Gustavobcc** [creesch/reddit-moderator-toolbox#530]
AKA the modmail link that's located in the "Moderation Tools" box in the sidebar. It does work on /r/subredditname/message/moderator/inbox

**Comment by agentlame** [comment]
A bit of help, even though @Gustavobcc was clear.  There are 2,152 ways to get to mod mail... context:

10:25 PM \<psdtwk> It doesn't??
10:25 PM \<Gustavobc> there's like 3 thousand ways to get to modmail
10:25 PM \<agentlame> ^
10:27 PM \<agentlame> psdtwk: you're thinking of /r/sub/message/moderator/inbox this is /r/sub/about/message/inbox
10:27 PM \<Gustavobc> ^
10:27 PM \<agentlame> See also.. fucking reddit.
