### ISSUE TITLE
"report spammer" and "view report in markdown" on user history does not always show

### ISSUE THREAD

**Issue by naxian** [creesch/reddit-moderator-toolbox#531]
"report spammer" and "view report in markdown" links on user history do not always show. It appears to only show on either the modqueue or unmoderated, but not if you access it directly from a subreddit. When it is not there you can press the "get comment history" link to have them appear.

showing fine on unmoderated - http://puu.sh/hOVNz/3a80816853.png

not showing on the subreddit - http://puu.sh/hOVQk/5f734f7073.png

pressing "comment history" makes them appear - http://puu.sh/hOVSA/a13b0817a0.png

Chrome, latest version. Latest version of toolbox. Using RES if that matters.

**Comment by creesch** [comment]
Oh great, this bug again... We have seen it before and though we had it fixed. We'll look into it.

**Comment by agentlame** [comment]
In addition to this issue, it has been reported that comment summaries don't work if OP has less than 100 comments: https://www.reddit.com/r/toolbox/comments/363vd2/release_toolbox_31_valuing_vulture/crbcjol
