### ISSUE TITLE
Usernotes always link to submission, not to specific comment

### ISSUE THREAD

**Issue by green-flash** [creesch/reddit-moderator-toolbox#534]
Since 3.1 If you open the usernotes dialog on a user's comment via [N], type a usernote text and leave "include link" checked, it will add a link to the submission, not the comment.

**Comment by agentlame** [comment]
Shit

**Comment by green-flash** [comment]
Looks like the bug is in the comments link regex for the squashPermalink function.

Changed from this:

    /\/comments\/(\w+)\/[^\/]+(\/(\w+))?\/?(\?.*)?$/

to this in 3.1:

    /\/comments\/(\w+)\/(?:[^\/]+\/(?:(\w+)\/)?)?/

Are you creating a non-capturing group and then trying to capture it? That's what it looks like to me.

**Comment by TheEnigmaBlade** [comment]
Two capture groups still exist: the first `(\w+)` for post ID and second `(\w+)` for comment ID. Maybe it's the removal of `(\?.*)?$`?

**Comment by agentlame** [comment]
This could also be a tbu.getthinginfo bug from here: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/usernotes.js#L203

Not on a computer I can test on.  But both that $body.on and squishpermalink really need some logging.

**Comment by green-flash** [comment]
Right. After a closer look the trailing slash is not optional. I guess this was intended:

    /\/comments\/(\w+)\/(?:[^\/]+\/(?:(\w+)\/?)?)?/

**Comment by agentlame** [comment]
Well, I'm guess it's not L203, huh?

**Comment by agentlame** [comment]
Wiat, which fix is correct?  O.o

**Comment by green-flash** [comment]
Both are correct. Enigma removed the matcher for the trailing slash entirely, I made it optional. Removing it completely is cleaner, since matching the trailing slash is as pointless as matching the query parameters. It's not something you care about.
