### ISSUE TITLE
{Nuke Comments} Make it not beta

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#535]

**Comment by agentlame** [comment]
This is assigned to @psdtwk and no one else is allowed to resolve this issue.  If he doesn't do it, the module is **never** allowed to leave beta.

I'm pulling co-founder rights on this.  @creesch it's a 10 for me.

**Comment by creesch** [comment]
That's fine, however the beta tag is appropriate considering @Dakta rewrote the entire thing from scratch.

**Comment by agentlame** [comment]
THAT'S NOT THE POINT!!!

**Comment by creesch** [comment]
That's ok, I am not touching it either way. @psdtwk is a big boy, he can do it.
