### ISSUE TITLE
intermittent issue with user search bar replicating over and over. 

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#543]
The first sighting can be found here:

https://www.reddit.com/r/toolbox/comments/36psre/bug_the_search_bar_keeps_multiplying/

greeny confirmed it here:

8:39 PM \<greenduch> http://i.imgur.com/RWFrytS.png hm thats weird
8:42 PM \<agentlame> greenduch: you're now the second person to report that (we got one we couldn't confirm).
8:43 PM \<agentlame> FF right?
8:43 PM \<greenduch> yes
8:46 PM \<agentlame> greenduch: that happens without using the search, correct?
8:46 PM \<greenduch> no just loading my userpage
8:47 PM \<agentlame> Only yours, or all?
8:47 PM \<greenduch> i just refreshed that page, agentlame , and it went away
8:47 PM \<greenduch> yeah im sorry i guess i cant replicate it
8:48 PM \<greenduch> yeah clicked through to a handful more userpages, not seeing it
8:50 PM \<agentlame> OP just replied he's on Chrome.  So no go there. 

The game's afoot, boys!

**Comment by creesch** [comment]
We haven't had a single new report about this, I am going to go ahead and close this.
