### ISSUE TITLE
Customizable Usernote Categories

### ISSUE THREAD

**Issue by Georgy-K-Zhukov** [creesch/reddit-moderator-toolbox#560]
Instead of the default categories such as "Spam Watch", "Spam Warning", etc. allow the names of the categories to be set in the subreddit's toolbox configuration.

**Comment by agentlame** [comment]
This has been requested before.  It's on our radar, but unlikely to happen anytime soon.  

The biggest issue is the note dialogue.  How does it work if a sub has 20?  The second is color selection.

**Comment by psdtwk** [comment]
I don't think he's requesting to make a neverending list of new categories. The request is to be able to define existing categories.

**Comment by agentlame** [comment]
Concatenate.

**Comment by TheEnigmaBlade** [comment]
Cleanup, cleanup...
