### ISSUE TITLE
The mod button on a comment disappears after you reply to the comment.

### ISSUE THREAD

**Issue by bjornenalfa** [creesch/reddit-moderator-toolbox#563]
The code that inserts the mod button puts it inside of the \<li> element that contains the reply button instead of before it. When you reply the reply buttons \<li> element gets cleared which removes the mod button.

**Comment by psdtwk** [comment]
On reddit: http://www.reddit.com/r/toolbox/comments/39qain/bug_after_replying_to_a_comment_the_mod_button/

**Comment by agentlame** [comment]
This is by design.
