### ISSUE TITLE
Highlight appropriate message reply when visiting a message permalink

### ISSUE THREAD

**Issue by teaearlgraycold** [creesch/reddit-moderator-toolbox#577]
Currently only the top message is highlight, regardless of the permalink you go to (even if it's a reply's permalink).

**Comment by agentlame** [comment]
Huh?

**Comment by teaearlgraycold** [comment]
If you click the permalink to a reply in modmail it'll bring you to the whole chain, with the top message highlighted.

**Comment by agentlame** [comment]
Oh!  You forgot to mention modmail in your post.  

Should be a simple thing to add.

**Comment by teaearlgraycold** [comment]
Since I managed to get my point across, it looks like I made this gfy for nothing :(

https://gfycat.com/SizzlingMagnificentHochstettersfrog

**Comment by Gustavobcc** [comment]
Nice loop tho
