### ISSUE TITLE
Comment queue tools also pulls comments made in ad threads

### ISSUE THREAD

**Issue by soronthur** [creesch/reddit-moderator-toolbox#581]
I noticed that when you click on queue tools in an user's history, it also loads the comments made in ad threads (example of an ad thread https://www.reddit.com/comments/33hg3n/you_do_have_time_to_read_download_a_free ).

**Comment by agentlame** [comment]
Very low impact.  Removing this from 3.3

**Comment by Geo1088** [comment]
This was fixed in bb062a9bf007705ffc2112ace03e16be9b7afb16.
