### ISSUE TITLE
Better error message when usernotes are full

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#588]
ref: https://www.reddit.com/r/toolbox/comments/3e47f9/notes_are_suddenly_not_saving/ (and the various posts like it)

The error should link to a wiki page to offer resolution tips (like pruning).

I'm setting this 3.3 but I may try to get it into 3.2.

**Comment by TheEnigmaBlade** [comment]
I wouldn't rush it. It won't really be necessary after S6 is released anyway.

**Comment by agentlame** [comment]
...for a little while.

**Comment by psdtwk** [comment]
[womp womp](http://sadtrombone.com/)

**Comment by creesch** [comment]
3.x

**Comment by TheEnigmaBlade** [comment]
Did thing with 81143798fce66109c6fef73fd45b434d48e9451f.
