### ISSUE TITLE
[BB] Don't show mod save button on subreddits the user doesn't mod

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#589]
I'm fairly certain the `moderator` class on `body` can be used. I should probably go fix this instead of making the issue, but it pads my stats. :smirk_cat:

**Comment by agentlame** [comment]
You can also use tbu.mysubs and an inArray.

**Comment by agentlame** [comment]
Actually you need to.  Because inboxes / mixed listing pages.

**Comment by agentlame** [comment]
IFTA: moderator class added to all `.thing`s would save us woulds of trouble.

**Comment by TheEnigmaBlade** [comment]
It utilizes the built-in distinguish button, and inbox input don't have it. Mixed listing pages, I guess so.

**Comment by agentlame** [comment]
Hrm... than why even check for the body class?  Just check for the button.

**Comment by TheEnigmaBlade** [comment]
The first only requires adding `.moderator` to the jquery selector, but the second doesn't work. It doesn't know if the distinguish button exists until after the comment is submitted, and by that point it doesn't matter if the mod save button is hidden.
