### ISSUE TITLE
/r/spiderbros queue creature

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#592]
Reach out to the /r/spiderbros mod team and find a proper smiling spider for a new queue creature.  

ref: http://www.reddit.com/r/toolbox/comments/3ecysy/release_toolbox_32_blackout_bear_now_with_100/ctdq6yx

**Comment by Gustavobcc** [comment]
[⁞)](http://i.imgur.com/eFXODNi.png)

**Comment by creesch** [comment]
We already selected a picture, should be in 3.3
