### ISSUE TITLE
rate limit warning does not display properly in Firefox

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#594]
ref: https://www.reddit.com/r/toolbox/comments/3efn3q/pruning_usernotes_doesnt_work/ctesxw9?context=4

And from my own testing in FF: http://i.imgur.com/UbzI0S5.png

My guess is something is breaking before this line is hit: https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L1062 

But I'm not sure what it is.  This issue is critical since mod button mass actions now go through `forEachChunkedRateLimit()`

@TheEnigmaBlade any thoughts on this?  There were no JS errors in FF's dev console that I saw.  But I'm not convinced that thing works.

**Comment by TheEnigmaBlade** [comment]
I'm getting it displaying like that too.

The error is `timer is not defined` on this line:

https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L1047

**Comment by agentlame** [comment]
Fixed in: d6a1d13dfbb5f5b8a2fabf8edf5595edb15228b6
