### ISSUE TITLE
New mod mail tagging is broken with native modmail threading

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#600]
It's not entirely broken, which why it was hard to notice.  In the name of efficiency we compare `$modmailThread.find('.entry:last')`s timestamp to our `lastChecked` timestamp.  If it's older, we stop processing that thread for new entries, if it's not, we traverse up the `.entry`s until we find one that is and break. 

Obviously, `.entry:last` is no longer the newest reply.  Which is why our testing of this was looked fine.  All the replies were in-line, just threaded.

There's two issues here: tagging new replies, and tagging a thread has having new replies.  The latter is simple, if @bsimpson63 adds a class to the last reply in a thread, we can use its timestamp to tag threads with new replies.

The former issue is harder.  To tag all the new replies as being new, we'd have to go back to processing **every reply** for its timestamp.  Which is a huge page load issue.

Thoughts?

**Comment by agentlame** [comment]
\o/ issue 600!  400 more and we get the "your project is shit" trophy on GH.

**Comment by bsimpson63** [comment]
It's easy to add a class to the most recent message in a thread, but you could also figure it out based on the message ids (the newest message has the highest id). Is that possible, or would you rather have the class?

**Comment by agentlame** [comment]
The class is much easier to `$('.last-reply .head').append('<stuff>')` and handle the entire page in one shot.  Since there can be up to 100 of them.  The other way we have to compare up to 100 thing_id's against their parents. (with `.last-reply` being whatever class you add.)

**Comment by bsimpson63** [comment]
https://github.com/reddit/reddit/commit/7656c7a7bd2c4e11894cb0678561867131df87d6 was just deployed.

**Comment by agentlame** [comment]
You are awesome! <3

**Comment by TheEnigmaBlade** [comment]
This is fixed, right?

**Comment by agentlame** [comment]
Nope: http://i.imgur.com/7gKsTCU.png
