### ISSUE TITLE
Open to PR's for expanding the Website Account History feature?

### ISSUE THREAD

**Issue by k3n** [creesch/reddit-moderator-toolbox#602]
Greetings,

I really love the new website account history feature, it's the best feature that I didn't know I was missing! 

I know that currently it only covers sites which are supported by reddit's embed feature, however, I've patched my local copy to cover medium.com -- specifically, `medium.com/@some_user`. I could probably add quite a few more in much this same manner and then submit a PR, I just want to know if it'd be welcomed before putting in the work.

Thanks for your time.

**Comment by agentlame** [comment]
It's hard to say without seeing the code, but it would likely be a valued addition.

**Comment by Dakta** [comment]
Since you've already written the code, it's definitely worth your time (all two minutes) to submit a pull request. That's no guarantee that we'll merge it, but based on the provided functionality we'd like to.

**Comment by k3n** [comment]
Sure thing, I was just waiting since @agentlame stickied my post in /r/toolbox, but alas, nobody else has chimed in.
