### ISSUE TITLE
replace all (most?) <button> usages with tb-generic-button

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#605]
Why?  Because this shit: http://i.imgur.com/DZ4hTec.png

I'm tagging this as 4.0, but it's something we can do slowly over various releases.

**Comment by creesch** [comment]
Hrm.. I see why. Two things though, do we want to replace submit buttons with generic buttons or a more specific style? Also, in some areas we actually make use of HTML form submit functionality, we need to be careful about not breaking that.

Otherwise a good idea.

**Comment by agentlame** [comment]
Good point, it's more of a case-by-case thing.  I'd say we should replace as many as we can.

I don't mind if subs want to style TB to fit their sub's style, but getting accidently styled is annoying.

**Comment by empyrical** [comment]
How widely supported is shadow Dom nowadays? I think this kinda thing might be a perfect use for that. Or if you're feeling crazy, you could have the ui be stuffed in an iframe if shadow dom is not an option

**Comment by creesch** [comment]
this is already done.
