### ISSUE TITLE
[DT] "Soft" colors don't work

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#613]
No errors in consoles, but "softred" and "softyellow" don't save.

**Comment by agentlame** [comment]
Should the work in domain tagger?  I made them for a different reason (which I no longer recall).

**Comment by TheEnigmaBlade** [comment]
They appear in the colors list, so they should either work or be removed.

**Comment by agentlame** [comment]
Why is that list named 'standardColors' if it's really domainTaggerColors?  I thought it was just where we put colors.

**Comment by creesch** [comment]
you made it...

**Comment by agentlame** [comment]
git blame, pls go.  I moved it from tbutils.js to tbui.js.

**Comment by creesch** [comment]
I mean you made domain tagger, a module you said yourself nobody else ever touched or cared about :P

**Comment by TheEnigmaBlade** [comment]
I, for one, *love* the domain tagged. <3

**Comment by agentlame** [comment]
Sometimes I wonder if you jerks don't plan things in private, just to mess with me.

**Comment by creesch** [comment]
oh for sure,  got an entire channel and sub dedicated to it.
