### ISSUE TITLE
[R] button shows up in modqueue

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#618]
![untitled](https://cloud.githubusercontent.com/assets/6052722/9427086/2efc8db0-492f-11e5-8374-b9f324e15129.png)

**Comment by agentlame** [comment]
The issue here are reported comments: http://i.imgur.com/4gtCLmB.png

A lame quick fix would be to have nuke rage quit on `tbu.isqueuepage`.

**Comment by agentlame** [comment]
Ya know... that isn't a bad fix at all.  Nuke shouldn't run on queue pages anyways.

**Comment by agentlame** [comment]
I like to call this "Neil talks to himself on GitHub."  It's a favored pastime.

**Comment by psdtwk** [comment]
:+1:
