### ISSUE TITLE
Could toolbox have a feature that shows the context of reported comments?

### ISSUE THREAD

**Issue by carlinha1289** [creesch/reddit-moderator-toolbox#624]
Same principle as to view the text of a self post, something moderators could click to view the context within which a comment was reported without having to open it in a new tab.
Thanks!

**Comment by creesch** [comment]
You mean like the parent comment and all that?

**Comment by carlinha1289** [comment]
Exactly.

**Comment by LiterallyWTH** [comment]
I think you're talking about RES's implementation where the parents are shown when you hover over the link?

That is done by copying the parent elements already on the page and will only show parents visible on the page currently.

I think the best path for this will be to make a small HTML engine for it and generate them out using comment_id.json?context=10000

**Comment by TheEnigmaBlade** [comment]
It would be *significantly* easier to to use jquery's `load(...)` to load the normal page with context and filter by comment area ID. Something like this:

```javascript
$contextContainer.load('https://reddit.com/r/funny/comments/3ni8h0/-/cvocvws?context=1234 #siteTable_t3_3ni8h0');
```

**Comment by LiterallyWTH** [comment]
That request pulls the whole shebang and jazz.  I agree it would be easier on us, but it would be heavy on the pipes, no?  I mean, for what we want to do, which I think really just requires author, text, and a permalink.

**Comment by Geo1088** [comment]
This was pretty much fixed in ac601b6a89f17273a69c3fecb9f8c5f4b97a76da.

**Comment by creesch** [comment]
Heh, someone has been digging through issues :) good catch.

**Comment by Geo1088** [comment]
That (145) has been bugging me for a while, figured I could knock out some
easy ones :P

**Comment by creesch** [comment]
It will never go down though. There are always issues we will never get to and new ones coming in. Still it [could be worse](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/190).
