### ISSUE TITLE
Mod log matrix doesn't work in /r/mod

### ISSUE THREAD

**Issue by Meneth** [creesch/reddit-moderator-toolbox#625]
/r/mod/about/log has a "toggle moderation log matrix" like all subreddits.
Clicking it works fine; all the mods show up and everything.
However, absolutely nothing happens when I hit "generate".

It is also broken in /me/f/mod/about/log/, though even more so there.
Absolutely no moderators are shown when going into the matrix view there, and all the bits below "show moderator filter" are missing entirely.

Edit: That second paragraph goes for all multireddits.

Old-school /r/sub1+sub2+sub3/about/mod is simply strange. It sort of works, but for a set of subs with a couple thousand mod actions in the last week, it only managed to load 221. Weird to say the least.

**Comment by TheEnigmaBlade** [comment]
To anyone else looking to fix the problem (I can't figure out the exact reason at the moment), the error causing the problem is `self` is undefined on line 175 when the generate form is submitted.

**Comment by andytuba** [comment]
It's because there's another `var self` inside the `renderMatrix` closure: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modmatrix.js#L228
