### ISSUE TITLE
Debug console close button shouldn't be playing hide-and-seek

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#627]
![](http://i.imgur.com/9akGsvv.png)

**Comment by agentlame** [comment]
This is likely realted to @Dakta's ongoing modbar work.

**Comment by TheEnigmaBlade** [comment]
I wasn't sure if that's the exact reason, so I made an issue just in case.

I *do* know his modbar work is causing `undefined` to be printed out four times a second, though.

**Comment by LiterallyWTH** [comment]
Make it looks it look more better like ![more betterer](http://i.imgur.com/po5Pzj7.png)
