### ISSUE TITLE
searching a user's profile makes the old mod button come back

### ISSUE THREAD

**Issue by amici-ursi** [creesch/reddit-moderator-toolbox#628]
as a side note, i have no idea which module does profile searching

**Comment by creesch** [comment]
re: sidenote 

The comment module does, since it searches comments :)

**Comment by agentlame** [comment]
I think there was some confusion on this one.  If I'm not mistaken, @psdtwk was to the new [M] button option:  https://reddit.com/#?tbsettings=modbutton&setting=showinusernamearea

Before searching: http://i.imgur.com/NukRdWW.png

After searching: http://i.imgur.com/g7xTG70.png

That said, this did fix the classic mod button placement, which was incorrect.

**Comment by creesch** [comment]
I fixed this earlier this week.
