### ISSUE TITLE
modsave button does not appear in r/mod

### ISSUE THREAD

**Issue by fritzly** [creesch/reddit-moderator-toolbox#629]
http://i.imgur.com/eibfp4A.png

**Comment by psdtwk** [comment]
Expand your screenshot. Where would one mod save in /r/mod?

**Comment by fritzly** [comment]
Sorry psdtwk I dont github

http://i.imgur.com/43YhJTM.png

It would be awesome to put it between the save and cancel like how you have it on the rest of reddit.  I and  many others reply out of r/mod and it would be easier if we could mod save.

**Comment by fritzly** [comment]
noo I didnt mean to close that

**Comment by psdtwk** [comment]
> psdtwk reopened this just now

i'm not sure if you can reopen issues.

**Comment by fritzly** [comment]
pls psdtwk u gotta
