### ISSUE TITLE
add "skip" option to mod button's error message

### ISSUE THREAD

**Issue by amici-ursi** [creesch/reddit-moderator-toolbox#630]
When using the mod button to do global actions, the action can fail for a number of reasons (lack of permissions in my case). If it fails for a subreddit, the script stops and asks

> would you like to retry?

**okay** or **cancel**

if you press **okay**, then it retries that action in that subreddit. if you press **cancel**, then it aborts the global action even through it hasn't processed the action in the remaining subreddits. Please add a **skip** option so the script can continue in the rest of the subreddits.

**Comment by creesch** [comment]
Hrm, I was under the impression it showed that message last. Guess I need to look at the actual code.
