### ISSUE TITLE
Title dot shows twice on user pages

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#633]
http://i.imgur.com/UMJLWOX.png

    <span class="tb-dt-little-dot">●</span>
    <span class="tb-dt-little-dot" style="color: rgb(52, 114, 53);">●</span>

**Comment by TheEnigmaBlade** [comment]
I can't reproduce this. Does it happen for all subreddits and domains?

**Comment by agentlame** [comment]
I've seen it happen twice, but I'm still trying to nail down what's up with the issue.  It's there, but it's elusive.

**Comment by agentlame** [comment]
I'm gonna close this, as I only saw it once.  We'll see if it comes back up in the beta.

**Comment by agentlame** [comment]
Damint: http://i.imgur.com/xyJU2JE.png http://i.imgur.com/0Ri26H7.png

If we can't figure this out for 3.3, I don't think it's a blocking.

**Comment by agentlame** [comment]
There it is: it's hitting for both domain and subdomain: `{"ver":1,"domainTags":[{"name":"imgur.com","color":"#DC00C8"},{"name":"i.imgur.com","color":"#347235"}],"removalReasons":"","modMacros":""}`.

It should always his subdomain before domain.
