### ISSUE TITLE
Let's use better modmail icons

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#637]
I made new modmail icons based on the ones from reddit's personal inbox. Let's make an option to use them instead of the modmail snoo.

![picture](http://b.thumbs.redditmedia.com/lbzECEbc-PSaMzFFSlLCY_3Me-zDbDeq_RTKFb69Ckg.png)

**Comment by TheEnigmaBlade** [comment]
That yellow makes it too hard to see what it is. I still can't figure that out.

**Comment by psdtwk** [comment]
It's the moderators icon from the sidebar 
![mnz5m7z](https://cloud.githubusercontent.com/assets/6052722/9972353/595ad1de-5e29-11e5-876b-acaa9e24e0bb.png).

**Comment by agentlame** [comment]
I'm not getting a modmail icon at all without having enabled or disabled the setting: http://i.imgur.com/hTwgJnE.png http://i.imgur.com/ifSCfyS.png maybe an issue with the default val.
