### ISSUE TITLE
Queue tools makes the results disappear from the subreddit search page

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#638]
To reproduce, 

1. go to a /r/yoursubredditname/search.
2. search for something
3. click on queue tools
4. the search results disappear.

**Comment by creesch** [comment]
Oh I think I know what this is.

**Comment by creesch** [comment]
Btw, depending on what the sub the result are from this can be expected behavior.

**Comment by creesch** [comment]
Yup it is, it hides the things you can't take mod actions on with queuetools.
