### ISSUE TITLE
Mod log matrix partially loads in multireddits

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#639]
Simular to #625 , the mod log matrix doesn't fully load in multireddits like https://www.reddit.com/user/amici_ursi/m/imagesofnetwork

![ss 2015-09-22 at 12 12 47](https://cloud.githubusercontent.com/assets/6052722/10011398/228e593a-60bf-11e5-9a49-cef5057fe159.png)

**Comment by TheEnigmaBlade** [comment]
It actually had absolutely nothing to do with #625. :stuck_out_tongue_winking_eye:

**Comment by psdtwk** [comment]
<3 @TheEnigmaBlade

**Comment by TheEnigmaBlade** [comment]
:+1:
