### ISSUE TITLE
Add post locking to Removal Reasons and Mod Macros

### ISSUE THREAD

**Issue by amici-ursi** [creesch/reddit-moderator-toolbox#647]
Post locking is in [limited beta](https://www.reddit.com/r/ModSupport/comments/3lzi4c/limited_beta_lock_a_post/) (we have it in /r/toolbox). It'd make a good addition to Removal Reasons

**Comment by agentlame** [comment]
Just a note on this, we can't add it until there is an API endpoint for it.  But there will likely be one before 3.3.  In addition, this should also be a supported action for macros.

**Comment by Geo1088** [comment]
This is already a thing. I added it to RR myself, and it seems like it's been in the macros for a while.
