### ISSUE TITLE
modmail limiting is broken if you click on the modbar icon

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#648]
Both the the reddit-native link, and the counter link are fine, but if you click on the actual icon, the URL doesn't include `?limit=n`.

This is likely caused by the new icon setting option.

**Comment by LiterallyWTH** [comment]
Does this happen all the time or just when you have modmail?

            if (count < 1) {

                // We are doing it like this to preserve other classes
                $tb_modmail.removeClass('havemail');
                $tb_modmail.addClass('nohavemail');
                $tb_modmail.attr('title', 'no new mail!');
                if (parseInt(modmailCustomLimit) > 0) {
                    $tb_modmail.attr('href', $tb_modmail.attr('href') + '?limit=' + modmailCustomLimit);
                }
            } else {

https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/notifier.js#L361

**Comment by LiterallyWTH** [comment]
It starts out correctly, see above the conditional.  It gets redone in notifier.js for some reason but the count link never comes along for the ride.


https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modbar.js#L142

**Comment by creesch** [comment]
I'll fix it,  probably broke it in the first place.
