### ISSUE TITLE
Tendency for trouble-sort to re-shuffle childless things

### ISSUE THREAD

**Issue by LiterallyWTH** [creesch/reddit-moderator-toolbox#654]
Not sure if it's a problem, but it looks bad.  Consider various options for fallback when comperator returns 0.

**Comment by creesch** [comment]
Is this a bug or an enhancement?

**Comment by LiterallyWTH** [comment]
For posterity, this just fixes it mostly.  Not sure why, but sometimes it still grabs 2-3 .things out of a long list of say 100, not sure if it scales with the size of the list, but it'll put those 3 things on rotation.  Mostly a non-issue in the context of its intended use.
