### ISSUE TITLE
It's not possible to choose date format

### ISSUE THREAD

**Issue by Meneth** [creesch/reddit-moderator-toolbox#655]
It's a bit annoying trying to decipher American-style dates on user notes.
It'd be nice if this was exposed in a setting somewhere.

**Comment by creesch** [comment]
Agreed, we'll probably can make it a global setting for wherever we show dates.

**Comment by agentlame** [comment]
We do use localized dates.  @Meneth are you referring to the hover preview or the date on the left when you open the usernotes dialog?

**Comment by Meneth** [comment]
In the dialog.

Sounds like your localization is failing, then, and needs an override option. Having my language set to American English doesn't mean I want American dates.

**Comment by agentlame** [comment]
It's not "our localization", it's JavaScript's: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/usernotes.js#L271

**Comment by Meneth** [comment]
Well, JavaScript messing up, rather. It probably assumes that my browser being set to American English means I want American dates.

Which is pretty silly considering American/International English is the English taught in a lot of European countries, none of which use the American date format.

**Comment by agentlame** [comment]
That is exactly what it is doing.  If you want different dates, correct your localization.

**Comment by Meneth** [comment]
I don't want my browser displayed in British English. There's no reason to tie date display to language.

**Comment by agentlame** [comment]
According to JavaScript there is.  Take it up with ECMA.

**Comment by Meneth** [comment]
Lots of programs, forums, etc. offer overrides for that very reason.

**Comment by creesch** [comment]
I promised we'll do this since it is pretty hard to correct from the browser. 

Should be easy enough anyway.

**Comment by creesch** [comment]
Don't be an ass

**Comment by agentlame** [comment]
This is a very clear issue of someone not wanting to set their browser correctly.  But if you want it to rot in issues that never get resolved, so be it.

**Comment by creesch** [comment]
As someone who uses his browser in his native language you never had to deal with this.  You cannot set localisation to this detail very easily.

**Comment by agentlame** [comment]
>As someone who uses his browser in his native language

That's the point of localisation.  You want Klingon dates, use Klingon localisation.  Overriding a single aspect of localisation is absolutely moronic. 

And tell me just how you plan on splitting time localisation from language in a way that makes sense at all, is easy to configure, and easy to implement in code.

This will sit forever with no action because it's completely moronic.  OP needs to set their browser correctly or take it up with ECMA.  We've done our due diligence with `toLocaleString`. 

This is my final comment on this non-issue.

**Comment by creesch** [comment]
@Meneth ... sooo what @agentlame was trying to say was 

> If you would be so kind to set chrome to "English (United-Kingdom)", you will see that after restarting chrome it is all good. 

my bad.
