### ISSUE TITLE
New setting main tab style is borked

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#662]
This how it looks, there are too many lines there.
![image](https://cloud.githubusercontent.com/assets/2502190/10559143/5e62d9fc-74e9-11e5-9385-e7eb013748de.png)

This is the cause

![image](https://cloud.githubusercontent.com/assets/2502190/10559155/8c199138-74e9-11e5-81bd-49f2123db307.png)

But I am not entirely sure where the extra paragraphs are coming from.

**Comment by creesch** [comment]
@Dakta or @agentlame

**Comment by agentlame** [comment]
It's me, but for the life of me, I can't figure out what is causing it.
