### ISSUE TITLE
Sorting on /r/subreddit/comments should be less jacked up

### ISSUE THREAD

**Issue by LiterallyWTH** [creesch/reddit-moderator-toolbox#664]
The problem seems to be related to RES NER, but maybe not, and it shouldn't.  I'll try to get a decent sample first.

**Comment by creesch** [comment]
Thanks for the remember! I wanted to work on sorting removal reasons and shortcuts. Not really related to this, but thought I would mention :P

**Comment by creesch** [comment]
@LiterallyWTH pls

**Comment by LiterallyWTH** [comment]
ok
