### ISSUE TITLE
'Global Action' button enabled regardless of setting

### ISSUE THREAD

**Issue by LiterallyWTH** [creesch/reddit-moderator-toolbox#666]

**Comment by LiterallyWTH** [comment]
It's cludged for now with '!important' in the inline style.  The problem is with specificity:

    body.mod-toolbox .tb-action-button {
        display: inline-block;
        /* ... */
    }

Is overriding the inline style.

**Comment by agentlame** [comment]
If only there were `!moreimportant`.  Surly that would never be abused.

**Comment by LiterallyWTH** [comment]
It's "fixed" though!
