### ISSUE TITLE
The ability to set either a default Removal Reason Msg Mode (Reply, PM, Both), or the ability to set that mode within the settings

### ISSUE THREAD

**Issue by D0cR3d** [creesch/reddit-moderator-toolbox#669]
There have been many times where one of us will choose to send a removal via Mod Mail for those 1 or 2 specific removal reasons, but want to continue sending via reply comments. Unfortunately that means finding something else to remove and hoping it saves that setting of back to the default. What would be great is in settings have us be able to set the default option to whatever we want, say reply comment, but if we change to mod mail for an item, the next time we remove something, it is back to the default unless we change the default, or we change for that instance at the bottom of the removal reason settings.

That would be the most preferred implementation of this however having an option in settings where we get to change the removal reason mode to another settings which stays there until you change it again either in settings or in the removal reasons popup would work as well.

**Comment by creesch** [comment]
So basically what you want is:

- a default setting in the settings menu for the sort of messaging done. 
- When choosing it for from the removal reason dialogue it should be only for that specific removal and return to the default afterwards?

**Comment by D0cR3d** [comment]
That is correct.

**Comment by D0cR3d** [comment]
This was implemented on 3.6 so going to close this. Thanks for adding this feature.
