### ISSUE TITLE
List of mods does not include currently selected mod when generated

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#670]
Reddit doesn't include the currently selected mod in the drop-down mod list from which mod matrix generates its own list of mods. Mod matrix needs to account for a mod being selected.

Note: It *is* possible to have nothing and "all" selected, but they are equivalent.

**Comment by agentlame** [comment]
I... wat?

**Comment by creesch** [comment]
Not a toolbox bug

**Comment by TheEnigmaBlade** [comment]
How is it not a toolbox bug? It doesn't account for a user being selected, which *is* toolbox's fault.

**Comment by creesch** [comment]
Reddit shouldn't exclude them from the list. But fine.

**Comment by agentlame** [comment]
What is the "issue"?

**Comment by TheEnigmaBlade** [comment]
The list of mods is generated from the "filter by moderator" drop-down. This is its default state:

![](http://i.imgur.com/KgL2KNF.png)

When you select a mod, they're excluded from the list:

![](http://i.imgur.com/i9lY5Lc.png)

Which makes sense from reddit's perspective: you can't select someone that's already selected.

**Comment by agentlame** [comment]
OK, so what is the "issue"?

**Comment by TheEnigmaBlade** [comment]
The selected person isn't included in the mod matrix.

![](http://i.imgur.com/c1SOd8O.png)

**Comment by LiterallyWTH** [comment]
Just confirmed.  I would call this a bug.

**Comment by agentlame** [comment]
So what's the issue?  Don't gen a report if you fuck with the data reddit gives.  

I said this in IRC hours ago.  If there is a URL param, just don't show the report button.  There's nothing else we can do.

**Comment by creesch** [comment]
Do we have a low low low priority tag,  this is one of those things that technically is a bug but I don't want to waste code and processing power on.

**Comment by agentlame** [comment]
It's not a 'bug'.   It's that people are excluding data they want.

**Comment by creesch** [comment]
Either way we already spent too much time on it for something that clearly hasn't been an issue until now.

**Comment by agentlame** [comment]
^

**Comment by creesch** [comment]
Also,  I am out of coffee.

**Comment by agentlame** [comment]
There... I fixed the tag.

**Comment by LiterallyWTH** [comment]
Found the culprit.  Posting for posterity.

https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modmatrix.js#L652
