### ISSUE TITLE
selected action is removed from ModMatrix, much like #670.

### ISSUE THREAD

**Issue by LiterallyWTH** [creesch/reddit-moderator-toolbox#672]
I'm guessing the cause is similar as well.

**Comment by agentlame** [comment]
We can fix this in the beta, it's p small.

**Comment by agentlame** [comment]
Do we want this fix in 3.3 or should we push it?  It's not that big of an issue.

**Comment by LiterallyWTH** [comment]
It's not big, but spooper easy.  I got this before the weekend is over.
