### ISSUE TITLE
macros should should prevent you from saving a macro with no title

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#675]
Currently this isn't prevented and results in a blank entry in the dropdown.

**Comment by creesch** [comment]
Is this a beta bug though? It has been in the previous versions and to check for it probably is a few lines of code. I rather fix it in a next version. 

I would even go as far as calling it an enhancement since macros still appear to work anyway.

**Comment by agentlame** [comment]
It's literally two lines of code.   Why not fix it?

**Comment by creesch** [comment]
I am not sure it is two lines of code to fix it in a userfriendly way. I am also not objecting, just thinking out loud. 
Also you should be sleeping, not replying to github issues in the middle of the night.
