### ISSUE TITLE
Removal Reasons comes up when spamming a post

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#682]

**Comment by creesch** [comment]
again?

**Comment by agentlame** [comment]
IKR?

**Comment by creesch** [comment]
<amici_ursi> agentlame: huh. i confirmed i on the front page of /r/underconstruction
        <agentlame> Oh.  I was in the mod queue.  That might be why we missed it. 
        <creesch> can confirm, it only happens when on a subreddit frontpage or new 
        <creesch> not when you are in the post or in the queue

**Comment by agentlame** [comment]
Actually, it looks like the `flat-list` spam button is the cause.  It's just that no queues use that style.
