### ISSUE TITLE
In modmail, sometimes the toolbox buttons work on the wrong user OR don't show on the other user

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#683]
The buttons work on the wrong user if the message header is `to {otheruser} [N] [M] [H] via /r/{subreddit}/`
![untitled](https://cloud.githubusercontent.com/assets/6052722/11260242/e11daa8a-8e2e-11e5-89a8-d93d6c058eb9.png)

The buttons do not show at all on the recipient if the message header is `from {otheruser1} [M] [N] [M] H via /r/subreddit/ to {otheruser2} [M]`
![untitled 2](https://cloud.githubusercontent.com/assets/6052722/11260244/e7ba79e0-8e2e-11e5-8483-e4fa782640d1.png)

**Comment by agentlame** [comment]
PEBKAC... dude, that's your message.  So it's showing your info.  This is by design, so you can seer your own user notes in mod mail.
