### ISSUE TITLE
Mobile version of toolbox

### ISSUE THREAD

**Issue by kain243** [creesch/reddit-moderator-toolbox#708]
Hi, new mod. Not sure if this is the right place to request this. I would love a mobile version of toolbox, even with no support. Its pretty essential as a mod and I do a lot of my modding from my phone. Hopefully you can make this happen. Thanks!

**Comment by creesch** [comment]
Not likely to happen soon, in the past I got it sort of working on mobile firefox but that was slow and required toolbox to be butchered in order to work properly. These days it is even more difficult due to firefox requiring addons to be signed.

**Comment by agentlame** [comment]
deferred or wontfix, pick one.

**Comment by creesch** [comment]
I haven't decided yet,  so it is in limbo.

**Comment by kain243** [comment]
Thanks anyway. It would be great to have at some point. As a moderator, I feel useless on mobile without toolbox.

Good luck :)


________________________________
De : creesch <notifications@github.com>
Envoyé : vendredi 29 janvier 2016 22:20
À : creesch/reddit-moderator-toolbox
Cc : kain243
Objet : Re: [reddit-moderator-toolbox] Mobile version of toolbox (#708)


I haven't decided yet, so it is in limbo.

-

**Comment by creesch** [comment]
Ok, even more bad news. It seems that mozilla crippled mobile addons even more since I have been going over it with the RES guys and we simply can' t get mobile addons to work with the latest tools. 

I am going to keep this issue open though so people can find it.
