### ISSUE TITLE
Mod Actions button - Missing selected subreddit, user flair, and send message options

### ISSUE THREAD

**Issue by D0cR3d** [creesch/reddit-moderator-toolbox#714]
https://i.imgur.com/bAQ3p3g.png

When using a url like reddit.com/comments/ ([example link](https://www.reddit.com/comments/49o13l/-/d0tf3jj?context=10000) if you click the mod button for a subreddit you mod, the the 'User Flair', 'Send Message' buttons don't show up, and the preselected subreddit for the sub you are in doesn't get auto selected, as if you are doing it from a sub you don't moderate.

**Comment by creesch** [comment]
pretty much expected behavior as it doesn't have the context of being in a subreddit. But it can probably be made nices.

**Comment by Geo1088** [comment]
Was this already added? I see the behavior you describe on that link (since I'm not a mod there), but I tested with a /r/anime thread and everything worked fine.

**Comment by Geo1088** [comment]
This is irrelevant now because Reddit redirects these links to /r/<sub>/comments/xxxxxx instead, so the sub will always be identified.
