### ISSUE TITLE
Error, failed to send PM when selecting remove reason

### ISSUE THREAD

**Issue by fcrdestiny** [creesch/reddit-moderator-toolbox#721]
I've been getting the following error pretty inconsistent now when trying to send a user a PM for reason their post has been removed.  

1. Click to remove
2. select reason (My options are PM (as sub).)
3. click send 

error, failed to send PM

I noticed it only happens in one sub I am a mod of and my permissions are limited to _flair, mail, posts, wiki._

Is this a limitation to toolbox that I'm not aware of?

I'm running toolbox for chrome and version  3.3.1.

Is there any logging I can look at to see why it's failing?

**Comment by creesch** [comment]
Closing this until we can confirm it is actually an issue. Support questions go to /r/toolbox where you already have posted.
