### ISSUE TITLE
mod buttons showing up on all posts

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#723]
I don't mod these subs: http://i.imgur.com/ptbGY8U.png

EDIT: 
Actually, it's all mod buttons: http://i.imgur.com/ArLkcg9.png maybe a tbutils issue?

**Comment by agentlame** [comment]
This fixed domain tagger, but [N] is still showing in all subs: http://i.imgur.com/ArLkcg9.png

(Also, I made a mistake, [M] is supposed to.)

**Comment by creesch** [comment]
probably because the check was also removed there, I'll check it out.
