### ISSUE TITLE
Expand the functionality of /r/(subreddit)/about/usernotes with new filters

### ISSUE THREAD

**Issue by Pyyric** [creesch/reddit-moderator-toolbox#726]
I'd like to filter the /about/usernotes page by any keyword or note category, not just username.

I've been collecting a list of good contributors with a note that simply says "👍". I'd like to sort by either 'good contributor' or '👍' on the usernote page so I can find them again. It's time for new moderators ;)

Also, being able to see the category / color for each user would be nice too.

**Comment by TheEnigmaBlade** [comment]
Added with #737?
