### ISSUE TITLE
Tabmenu List Item Class/ID

### ISSUE THREAD

**Issue by mmolad** [creesch/reddit-moderator-toolbox#729]
Hi there,

Toolbox adds list items to the tabmenu for functionality. I get why its there, but sometimes we need to do things to the tabmenu that make sense for the default functionality - sorting threads, filtering, etc. - but don't make sense for mod buttons.

In order to correct this, I can target the metrics list-item via .tb-metrics but the Queue Tools one does not have an identifier.  This makes it impossible to do things like change the order via flexbox, etc.

Can you please also add a class to the queue tools parent list item so I can account for it in my theme designs? Let me know if you need clarification.

**Comment by agentlame** [comment]
Use `.tb-queuetools-tab`

**Comment by mmolad** [comment]
This doesn't appear to resolve the issue; the class was added to the link, when it should be on the parent list item. The commit reads:

    +        $('.tabmenu').first().append($('<li><a href="javascript:;" accesskey="M" class="modtools-on tb-queuetools-tab">queue tools</a></li>').click(addModtools));

It should instead read:

    +        $('.tabmenu').first().append($('<li class="tb-queuetools-tab"><a href="javascript:;" accesskey="M" class="modtools-on">queue tools</a></li>').click(addModtools));
