### ISSUE TITLE
`Website Account History` feature is not working

### ISSUE THREAD

**Issue by RomanHargrave** [creesch/reddit-moderator-toolbox#732]
The "History Button" website->account history viewer is not working.

This is somewhat hindering my personal all-out war against blog spam in /r/linux, /r/programming, and /r/java.

**Comment by RomanHargrave** [comment]
Well not quite as expected...

**Comment by creesch** [comment]
Can you please make a post about this on /r/toolbox and explain it a bit more so we can determine if it is really a bug or something else?

**Comment by RomanHargrave** [comment]
It was a bit out of confusion. BTW is there support for viewing a list of users that post a domain?
