### ISSUE TITLE
Submissions and comments in /r/spam should be hidden when on a profile and the 'hide mod comments' button is clicked. 

### ISSUE THREAD

**Issue by noeatnosleep** [creesch/reddit-moderator-toolbox#735]

**Comment by agentlame** [comment]
We might also want to change the phasing to 'hide mod actions'.  Thoughts?

**Comment by creesch** [comment]
cool

**Comment by noeatnosleep** [comment]
Sounds good to me.

**Comment by geo1088** [comment]
Got this working in my fork, should I PR now or do you guys want to discuss more?

**Comment by agentlame** [comment]
Sweet.   I think it's as discussed as need be.   Open a PR.

**Comment by geo1088** [comment]
@agentlame
