### ISSUE TITLE
Mod counters in the bottom right do not change click destination for /me/f/mod

### ISSUE THREAD

**Issue by noeatnosleep** [creesch/reddit-moderator-toolbox#739]
[Here](https://github.com/creesch/reddit-moderator-toolbox/issues/505) the counter was changed to work with /me/f/mod, but when you click it, you go to your old queue. Most of us using the /me/f/mod counter have to go to the queue manually instead of clicking the number. (I use a bookmark.)

[Here's the commit for the counter change.](https://github.com/creesch/reddit-moderator-toolbox/commit/41446fb739a60b3abeb27231a0b8372e3180f068)

**Comment by agentlame** [comment]
The issue is that modbar.js is where the links are generated.  We didn't apply the the same logic from that commit to here: https://github.com/creesch/reddit-moderator-toolbox/blob/master/extension/data/modules/modbar.js#L137
