### ISSUE TITLE
gulp build cleanup not working due to undefined variables.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#741]
@TheEnigmaBlade can you have a look at it. 

https://github.com/creesch/reddit-moderator-toolbox/blob/master/gulpfile.js#L43 <-- this line doesn't work as the del variable isn't defined. But I also have no idea how it is supposed to work and considering that I assume you had it working you do.

**Comment by TheEnigmaBlade** [comment]
Whoops, I think I deleted the require when cleaning up to commit.
