### ISSUE TITLE
Remove stupid 'send as sub' from removal reasons.

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#742]
This 'feature' is hated by everyone.  It shits up modmail and is basically awful.

NB: when removing the feature, it should be commented out, not deleted.  I have a bad feeling like three mods of small subs will scream that it's their normal workflow.  If enough people whine, we may need to make it some weird 'advanced' option, or something.  As such, I want the code for it to still be there.

**Comment by agentlame** [comment]
Oh, and it will likely need some setting migration code in `TBUtils`.  I'm not sure.

**Comment by amici-ursi** [comment]
Or at least rename to "send from modmail"

**Comment by agentlame** [comment]
That doesn't resolve anything, though.  The issue is that mods hate it when co-mods enable using it.  `send as /r/{sub}` isn't confusing anyone, it's just a shit feature.

**Comment by TheEnigmaBlade** [comment]
I've also told co-mods to stop using it under threat of removing the feature.

I'm not sure it should actually be removed, though. Maybe a bright red warning when you select it, or something.

**Comment by creesch** [comment]
Considering it no longer sticks and is moved to settings now I am going to close this issues. I'll do one last thing, I'll make the setting advanced.

**Comment by creesch** [comment]
did the thing.
