### ISSUE TITLE
MMP locks up on load and never exits longLoadNonPersistent()

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#743]
Seems to happen on this line: https://github.com/creesch/reddit-moderator-toolbox/blob/master/extension/data/modules/modmailpro.js#L935

`VM15010 modmailpro.js:935 Uncaught ReferenceError: threadOnExpand is not defined`

**Comment by geo1088** [comment]
What does the statement inside that condition even do? It seems like either a new setting for that has to be made, or remove the condition and do it anyway.

**Comment by creesch** [comment]
I dunno but account to blame it has been in there since at least 2014

**Comment by agentlame** [comment]
Oh, i didn't even pay attention to that var name.  That's left over from our old threading support, before reddit added it natively.

**Comment by geo1088** [comment]
So can the whole thing just be removed then?

**Comment by agentlame** [comment]
Probably.  Delete it and see what explodes.

**Comment by geo1088** [comment]
Removing it breaks nothing. Actually, it looks like it was a broken feature even when the setting  existed, because just executing the code inside the `if` does nothing (it references a class, `..tb-thread-view`, that doesn't even appear to exist in MMP).

Opening #744 for this.

**Comment by agentlame** [comment]
This is fixed, correct?

**Comment by geo1088** [comment]
Yeah.

**Comment by agentlame** [comment]
Luu

**Comment by creesch** [comment]
No fixy fix?

**Comment by geo1088** [comment]
Oh no what'd I break now

I swear it was working before, what's up with this being re-opened?

**Comment by agentlame** [comment]
FFS, I still had this page open on my phone, in my pocket.

**Comment by geo1088** [comment]
Lol, nice.
