### ISSUE TITLE
better buttons distinguish/sticky behavior

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#745]
Still broken yo, needs fixing for 3.4 or people will likely be "what they hell have you guys been doing?!". Which is a valid question regardless...

**Comment by geo1088** [comment]
I was looking into this the other day, saw some other smaller issues I'll probably be taking care of today but I'll be taking a closer look at this one soon-ish probably.

**Comment by creesch** [comment]
I rather take a look at it myself. The flow of the entire thing is uhm "interesting" to say the least because of how the admins build it.
