### ISSUE TITLE
Remove "edit automoderator config" tab from subreddit config

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#756]
The tab seems pointless to me now that a link to the automoderator config exists in the sidebar moderation tools list. All the other tabs are specific to toolbox.

The config tabs also wrap to a new line, and removing the automod tab would prevent that from happening.

**Comment by agentlame** [comment]
False.  This allows you to edit the config from any page without leaving it.   Also from the mod queue.  


Pls 2 revert.

**Comment by creesch** [comment]
No, I still use this fairly often as it is easier as I don't have to leave the page.

**Comment by agentlame** [comment]
Oh, this wasn't a commit.
