### ISSUE TITLE
Calculate "account website history" percentages based on total submissions.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#758]
Currently it shows a percentage that is based on the total of accounts found, which of course does give a bit of a weird impression. It is probably better to calculate the percentages based on the total submissions.

**Comment by agentlame** [comment]
I'd go so far as to call this a bug.   That's completely incorrect behavior.

**Comment by creesch** [comment]
Going to try and work this one in for 3.4
