### ISSUE TITLE
Report: include media_author

### ISSUE THREAD

**Issue by joeymavity** [creesch/reddit-moderator-toolbox#759]
Hi - this may be a dupe of https://github.com/creesch/reddit-moderator-toolbox/issues/404 or a dependency on that, I'm not sure. But it would be nice if, in the reports that go to /r/spam, there was a column that showed media_author as per http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx3wkpc9_don-t-need-pretty-still-of-pretty-girls-3-v_fun

This would help identify someone who is trying to monetize clicks via one or two youtube channels v. someone linking to OC. It would also help in adding the media author's to /r/yt_killer or our own automod filters.

**Comment by creesch** [comment]
There is absolutely no use for that though, the reason it sends a report to /r/spam is due to legacy reasons when /r/reportthespammers was still in use and run by volunteer mods who looked at the submissions. With /r/spam there is just the automated bot.
