### ISSUE TITLE
"Mod Save" option to distinguish and sticky a moderator comment

### ISSUE THREAD

**Issue by SHBelsky** [creesch/reddit-moderator-toolbox#762]
I love the existing "Mod Save" feature, but it would be super helpful to have the same functionality but also automatically sticky the comment in a comment thread. 

This could be side-by-side with the existing "Mod Save" button and be something like "Mod Save + Sticky" in order to distinguish and sticky a comment, as it's currently available for moderators to do just that with top-level comments.

Thanks!

**Comment by Geo1088** [comment]
Gonna add this tomorrow assuming I don't get sidetracked by other stuff.

**Comment by amici-ursi** [comment]
https://www.reddit.com/#?tbsettings=bbuttons&setting=enabledistinguishtoggle

**Comment by creesch** [comment]
That is something different @amici-ursi, they are talking about the mod save button .
