### ISSUE TITLE
Is there a way to automatically copy the permalink of the removed comment into a ban note and ban message?

### ISSUE THREAD

**Issue by throwaway12345321** [creesch/reddit-moderator-toolbox#778]
It'd be nice to have that shortcut

**Comment by Geo1088** [comment]
You might find [this thread](https://www.reddit.com/r/toolbox/comments/58vf9u/request_option_to_include_link_to_post_the_mod/) interesting.

**Comment by amici-ursi** [comment]
Duplicate of #343

**Comment by agentlame** [comment]
Well shit...

**Comment by agentlame** [comment]
This is consolidated with #343 into #779.
