### ISSUE TITLE
Allow use of text macros/insertion in the "Mod Actions" box

### ISSUE THREAD

**Issue by Wegerich** [creesch/reddit-moderator-toolbox#779]
By this I mean the box that appears when clicking "mod" underneath each comments in a sub one moderates, which can be used to issue bans. 

I very regularly put in the same text and ban about 30-50 people a week, so being able to quick paste a template in there would be very useful. 

Things like:

`You have been banned for [this]() post.`  
`Please read the [rules](/r/{subreddit}/about/rules) before posting in this subreddit again.`
`You must find out the rules before participating in any community, online or offline`

I post on a daily basis, and reducing the number of clicks for this would be marvellous, as well as reducing the number of time consuming appeals from users who do not realise that the comment permalink I pasted needs to be clicked on.

It seems like macros would be a good solution to issues like [this](https://github.com/creesch/reddit-moderator-toolbox/issues/779) without needing clever programming to detect the permalink of the comment - once you have some template text it's easy to click and drag the link **and** have it look neat.

**Comment by agentlame** [comment]
I've got this.  I know how I want to do it.  

The short is: per-sub pre-defined ban messages and notes that can make use of macros.   They will be stored in /w/toolbox and configured via tbconfig.

**Comment by Wegerich** [comment]
It's quite important to me to be able to edit the message before sending, so having something like the removal reasons for posts wouldn't work in this case, it would need to be similar to the macros system used by RES (and toolbox?)

**Comment by agentlame** [comment]
This is a feature that pre-populates the fields.  You will be able to change them as you see fit.

**Comment by creesch** [comment]
@agentlame 

Will you have time to do this soon? You already made the code, it still needs an interface. 


I have been fixing bugs here and there and a bunch more stuff so I would actually want to do a small release soonish. https://github.com/creesch/reddit-moderator-toolbox/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.5
This is one of the remaining issues I can't do for 3.5 as I don't know what you had in mind. If you don't have the time we'll move it to 3.x of course.

**Comment by agentlame** [comment]
This still needs a UI, but the feature is complete.  We left this at an impasse because we weren't sure how/where we wanted to put the settings for it.  My idea was to take the config welcome screen and put this and the domain tags settings in there, since they don't need full tabs.

**Comment by creesch** [comment]
yeah as I said

> You already made the code, it still needs an interface. 

Question is if you will have time to work on it. With my time available I figured I could tackle the remaining things open for 3.5 but was not sure about this. 

If you think you don' t have the time for it I'll try to have a go at it but otherwise we could move it to a next 3.x as nobody is currently missing it.

(we could use some more active devs)

**Comment by creesch** [comment]
Actually, I guess I could make a UI regardless, I just realized it isn't that much code to begin with and probably made it out to be bigger than it is.

**Comment by agentlame** [comment]
I mean, I can make the UI, but it's just gonna be another tab and like two text fields.

**Comment by Wegerich** [comment]
In case you're interested in some feedback on a possible UI, the current tab for issuing bans would be a great place to put it - just a dropdown with fill options (defined elsewhere in toolbox) and a "fill" button would probably be all the functionality I'd need.

**Comment by creesch** [comment]
That is not how it currently is implemented. What @agentlame build is more of a single "macro" that will pre fill the ban reason with text where you can use tokens. So from your example it would be 

`You have been banned for [this]({permalink}) {{kind}}.
Please read the [rules](/r/{subreddit}/about/rules) before posting in this subreddit again.
You must find out the rules before participating in any community, online or offline`

There will not be a dropdown where you can select multiple macros.

**Comment by Wegerich** [comment]
Ah, sorry, I misunderstood. That is also excellent, and really, really excellent that it includes the permalink. It's not common for me to vary the message much more than adding a specific rule number. 

Thanks for working on this :)
