### ISSUE TITLE
ignore reports on first approval of submission/comment

### ISSUE THREAD

**Issue by alienfromEuropa** [creesch/reddit-moderator-toolbox#781]
Constantly have to hit "reapprove" and then "ignore reports" after something has already been approved:

![an example of having to painstakingly hit the approve button twice](http://i.imgur.com/LpGL0dj.png) 

I would like a way to automatically ignore reports on the submission/comment approval the FIRST time. Either just in the toolbox settings or having the ignore reports button always there next to "approve". It seems like in order to ignore reports, you have to approve it twice for the second report. In a very large sub, this becomes very annoying when you've got a very long queue. Any help will be appreciated. Thanks!

**Comment by creesch** [comment]
https://www.reddit.com/#?tbsettings=bbuttons&setting=ignoreonapprove
