### ISSUE TITLE
Immediately return from the setInterval if !consoleShowing 

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#783]
I'm a dumbass.  [This](https://github.com/creesch/reddit-moderator-toolbox/blob/master/extension/data/modules/modbar.js#L352) should return in the first line `if (!consoleShowing)`.

Should be a big performance improvement and fix some issues with the new console using CodeMirror.

**Comment by Geo1088** [comment]
So literally just that?

**Comment by agentlame** [comment]
...yeah.  No idea why I made an issue for it, when typing the fix was quicker.  :/

**Comment by Geo1088** [comment]
:V
