### ISSUE TITLE
Usernotes appear to be broken in new modmail for firefox. 

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#784]
The usernotes button loads but no usernotes, it is also not possible to create a new note. 

At least in 3.4, have not been able to test 3.5 yet. 

I am suspecting firefox itself to be the cause has it did work before.

**Comment by creesch** [comment]
3.5 seems to work just fine in the developer version of firefox. 

Weird. @Geo1088 can you test as well?

**Comment by Geo1088** [comment]
Works in 51 (current dev), broken in 49 (current release).
