### ISSUE TITLE
Feature request: Choose default reply option in new modmail

### ISSUE THREAD

**Issue by leviroth** [creesch/reddit-moderator-toolbox#797]
I'm referring to the Reply as myself / Reply as the subreddit / Create a private note option. Some people like, for example, to reply as the subreddit for reasons of personal privacy, and this would make it easier to avoid exposing your own username by accident.

In a similar vein, there could be an option to have "Create a private note" become the default when it's what was last used in the conversation. That way you don't try to respond to some private comment and accidentally send it to the user.

**Comment by Geo1088** [comment]
These both sound pretty doable.

**Comment by creesch** [comment]
I am not sure I want to implement it exactly like that, but something similar has crossed my mind. 

Setting a default is possible but might not please the admins so we would need to check that. 

When the last reply was a private note and you don't select that option I was thinking about a warning. Or possibly move the reply button so people can't use muscle memory.

**Comment by creesch** [comment]
This is implemented with https://github.com/creesch/reddit-moderator-toolbox/commit/c76e7b4045622e126d8d89bdc9e7def356b52883
