### ISSUE TITLE
User notes - display date format

### ISSUE THREAD

**Issue by Laogeodritt** [creesch/reddit-moderator-toolbox#798]
Currently, in user notes (as displayed beside the username and from the "N" button on user submissions on a sub you moderate), the date format appears to be hard-coded to the short format DD/MM/YYYY. This is not internationalisation-friendly, even if we restrict to native English-language users: for example, the U.S. uses MM/DD/YYYY or MM/DD/YY format, and others yet may prefer the ISO8601 YYYY-MM-DD format. (I personally always have to stop and think about whether it's MM/DD/YYYY or DD/MM/YYYY, so reading these dates is always slow for me.)

The option to fully custom-define the date format, or at least a dropdown of common formats, would improve date legibility for different users internationally.

![image](https://cloud.githubusercontent.com/assets/1468874/21536314/47c369c2-cd4f-11e6-81cc-9edb114dae57.png)

**Comment by creesch** [comment]
It is displayed according to your browser's locale. You can change that in your browser settings, so we will not change that.

**Comment by Laogeodritt** [comment]
Ah, all right—didn't realise browsers held their own locale settings separate from the OS. I just saw the date didn't correspond to my OS settings and assumed it was a hard-coded format string somewhere.

**Comment by creesch** [comment]
Yeah it is a bit confusing in that regard, in chrome it is basically tied into the language you selected. You have US english set probably and if you change it to UK english it will display a different format.
