### ISSUE TITLE
Logsub not working from /about/unmoderated

### ISSUE THREAD

**Issue by Hareuhal** [creesch/reddit-moderator-toolbox#804]
When trying to remove a post with logsub use from the unmod queue, it returns an error "error, failed to create log post".

However, when removing from that post directly - the post is removed and the log is created in the correct subreddit.

I found a post on /r/toolbox from 3 weeks ago which details this information pretty extensively and had 0 replies and 2 upvotes. 

https://www.reddit.com/r/toolbox/comments/5kl8qf/inconsistent_log_sub_posting/

This is a pretty user-breaking experience for subs using logsubs.

Wasn't able to find any current bug reports for it.

**Comment by creesch** [comment]
https://github.com/creesch/reddit-moderator-toolbox/pull/800

This is fixed in the next release.
