### ISSUE TITLE
Mod-macros: failure to distinguish non-top level comment when sticky option active

### ISSUE THREAD

**Issue by multubunu** [creesch/reddit-moderator-toolbox#808]
If a macro with 'sticky comment' option selected is applied to a non-top level comment, the message 'failed to distinguish post' is briefly displayed, and the post is not distinguished.

This creates problems with macros addressing transgressions that can be both post or comments. An example would be PI, where a facebook picture with exposed names can be posted both as a post or a comment.

The workaround is maintaining separate quasi-identical macros for the two situations (with and without sticky option), which is a bit cumbersome. It would be nice to have 'sticky when possible' functionality, like for 'lock post' (which does nothing when macro is not top-level comment).

**Comment by Geo1088** [comment]
Ah, crap, we should be checking whether or not the comment is actually top level before sending the distinguish call. This shouldn't be too bad, I'll take a look right now.

**Comment by Geo1088** [comment]
That was easy. Fixed for next release, thanks for the report!

**Comment by multubunu** [comment]
Whoa, that was fast!

Thanks for this and everything you guys are doing, this tool is extremely useful!
