### ISSUE TITLE
Mod macros: Integration with user notes

### ISSUE THREAD

**Issue by multubunu** [creesch/reddit-moderator-toolbox#810]
Feature request.

When responding to a transgression, most of the time a user note will be added as well. It would be nice to have such integration in mod macros.

I imagine having an extra button in the macro definition box - 'add usernote', and one or two text fields for the note itself and the 'tag' (e.g. 'Abuse Warning').

**Comment by agentlame** [comment]
Sorry, automated user notes are something we have decided not to add.
