### ISSUE TITLE
Removal reasons: no way back from accidentally pressing 'remove'

### ISSUE THREAD

**Issue by multubunu** [creesch/reddit-moderator-toolbox#812]
When pressing 'remove' on a post, the user is presented with a dialog box that includes the buttons 'save', 'no reason', and 'cancel and approve'.

If the button was pressed accidentally, there is no option to cancel removal.

Closing the tab or pressing the 'back' button results in deletion of the post.

Seen on Firefox 51.0.1 with mod-tools 3.5.0 and RES 5.4.2. Other possible interference could be NoScript 2.9.5.3. I'll provide full add-on list and further testing if you cannot reproduce.

**Comment by Geo1088** [comment]
As far as I can tell, this is intended behavior. It makes the "remove" and
"approve" buttons into one-click actions, and also brings up the dialog
immediately.

That said, I've been bothered by this plenty myself. I think it might not
be a bad idea to cancel the removal when the dialog comes up and not remove
it until you hit "save".

**Comment by multubunu** [comment]
Clicking 'remove' accidentally is a relatively common occurrence, especially if one has RES. The page takes a while to load and buttons/links keep moving, hitting the wrong one may happen when you're hasty.

A plain 'cancel' button in the box would help prevent accidental deletions.

**Comment by Geo1088** [comment]
Yeah, agreed.

**Comment by creesch** [comment]
There will be no cancel button as yes is already clicked when the popup opens. I am on my phone but will link to the reasoning when this came up last time.

**Comment by creesch** [comment]
https://www.reddit.com/r/toolbox/comments/5s8ahi/slug/ddd7lll

**Comment by multubunu** [comment]
Well, the workaround is this:

When clicking 'remove' the dialog comes up, there is a text in the top-left corner saying 'Removing: <post title>'. Clicking <post title> takes you to the post's page where you can 'approve' it (it's already removed).

**Comment by creesch** [comment]
Not sure what you just said.

**Comment by multubunu** [comment]
Me neither :D

Just press 'cancel and approve', totally forgot about that option.

**Comment by Geo1088** [comment]
Oh, slightly related: Whatever happened to the plan to make the RR selection window not disable the rest of the page?

**Comment by creesch** [comment]
Still a plan at this point.
