### ISSUE TITLE
Change all multiline strings to ES6 format.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#813]
So instead of 

    let string = 'line 1\
      line2\
      etc';

Use backticks and do 

    let string = `line 1
      line2
      etc`;

**Comment by agentlame** [comment]
Is this string format supported *for extensions* by all of the browsers we support?  Opera, Chrome, FF (and Edge, in the furure?)

**Comment by creesch** [comment]
Yes.
