### ISSUE TITLE
Allow mod save button from inboxes

### ISSUE THREAD

**Issue by Geo1088** [creesch/reddit-moderator-toolbox#820]
Related to #589 and its fix d1ad5ddcf8f427ecb5c2d625a975c19076a713e5 - It appears inboxes and such were known to be excluded from this; is this by design or can I add it back in those places? I'm thinking rather than using the `.moderator` body class we can filter the save buttons by whether or not their thing's `data-subreddit` is a mod sub.

Something like this for [these lines](https://github.com/creesch/reddit-moderator-toolbox/blob/f0349eaf6fb74e1f2f4f3565bbc32e4e09c95f97/extension/data/modules/betterbuttons.js#L94-L104):

```js
function addButtons () {
    var $usertextButtons = $('.commentarea>.usertext .usertext-buttons');
    $usertextButtons = $usertextButtons.filter(function () {
        return TBUtils.mySubs.indexOf($(this).closest('.thing').attr('data-subreddit')) > -1
    })

    // Add buttons to DOM...
}
TBUtils.getModSubs(addButtons)

// Click listeners...
```

**Comment by creesch** [comment]
Uh... I think they are excluded since in the inbox you can't distinguish right away. Also with how weird inboxes are on reddit there might have been some issues.

**Comment by creesch** [comment]
Also testing something really quick. pls ignore.

**Comment by Geo1088** [comment]
I mean, the distinguish button is still there after you comment, so unless the mutationobserver is doing something I don't understand (which is likely) it should be fine.

**Comment by creesch** [comment]
Feel free to poke around, but this is probably one of those areas where in a few months we have to redo the entire thing anyway.

**Comment by Geo1088** [comment]
If it lets me do what I think it will, this will be easy. If not I'll give up. :P

**Comment by creesch** [comment]
fair enough

**Comment by creesch** [comment]
Also one more test to something totally not related to toolbox.

**Comment by Geo1088** [comment]
oh wait this is stupid. The inbox clones the reply field when you hit the "reply" button, so we can't actually make it different for each item easily. So this was intentional.
