### ISSUE TITLE
GEO1088 BROKE ALL THE THINGS AND IT IS TERRIBLE! 

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#843]
See https://git.io/v7ijR

**Comment by Geo1088** [comment]
[me_irl](https://cdn.discordapp.com/attachments/159404315243577344/344534851430514698/tumblr_o2hrtmZXWZ1tzlep2o1_500.gif)

**Comment by creesch** [comment]
Hey, look at it from this angle. At least you haven't had the pleasure of publishing a completely broken build to the chrome store. I have.

**Comment by Geo1088** [comment]
Lmao, nice.
