### ISSUE TITLE
Mod Invite Bug

### ISSUE THREAD

**Issue by xCapRx** [creesch/reddit-moderator-toolbox#849]
I've had multiple incidents where I've sent mod invites to one redditor and that redditor receives mod invites for at least 2 subs. Can this be fixed please?

**Comment by creesch** [comment]
Sorry, but we are going to need more information as I have never encountered this issue. 
Can you replicate it and make screenshots of each step? thank you.

**Comment by creesch** [comment]
Closing the issue since this is not enough to work with and I cannot get it to replicate.
